Repository triplea-game/triplea, pull requests merged in 2018-02, with the labels that each got.

#2950 Parallel OddsCalculator
  src/main/java/games/strategy/engine/framework/GameDataUtils.java
  src/main/java/games/strategy/triplea/ai/fastAI/FastOddsEstimator.java
  src/main/java/games/strategy/triplea/ai/proAI/ProAi.java
  src/main/java/games/strategy/triplea/oddsCalculator/ta/AggregateResults.java
  src/main/java/games/strategy/triplea/oddsCalculator/ta/ConcurrentOddsCalculator.java
  src/main/java/games/strategy/triplea/oddsCalculator/ta/DaemonThreadFactory.java
  src/main/java/games/strategy/triplea/oddsCalculator/ta/IOddsCalculator.java
  src/main/java/games/strategy/triplea/oddsCalculator/ta/OddsCalculator.java
  src/main/java/games/strategy/triplea/oddsCalculator/ta/OddsCalculatorPanel.java
  src/main/java/games/strategy/util/CountUpAndDownLatch.java
Labels: PR: <WIP>

#2991 Simplify ClientFileSystemHelper#getRootFolder()
  src/main/java/games/strategy/engine/ClientFileSystemHelper.java
  src/test/java/games/strategy/engine/ClientFileSystemHelperTest.java
Labels: PR: <TESTING>

#2997 Fix #2980
  src/main/java/games/strategy/engine/framework/startup/ui/PbemSetupPanel.java
  src/main/java/games/strategy/engine/framework/startup/ui/SetupPanel.java
Labels: PR: <TESTING>

#2999 Add OSX protocol handler
  game-core/build.install4j
Labels: PR: <TESTING>

#3055 remove unused 14
  game-core/src/main/java/games/strategy/triplea/ai/proAI/ProData.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/ProPurchaseAi.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPurchaseOption.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPurchaseTerritory.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProTransport.java
Labels: PR: <BUILD PASSED>

#3064 Remove always true if condition
  game-core/src/main/java/games/strategy/triplea/ui/display/TripleADisplay.java
Labels: PR: <BUILD PASSED>

#3051 Remove unused methods and do-nothing initiliaze method
  game-core/src/main/java/games/strategy/engine/display/IDisplay.java
  game-core/src/main/java/games/strategy/engine/framework/AbstractGame.java
  game-core/src/main/java/games/strategy/engine/lobby/server/LobbyServer.java
  game-core/src/main/java/games/strategy/triplea/ui/display/HeadlessDisplay.java
  game-core/src/main/java/games/strategy/triplea/ui/display/TripleADisplay.java
  game-core/src/test/java/games/strategy/security/TestSecurityUtils.java
Labels: PR: <BUILD PASSED>

#3058 Remove unused game data parameter and always null stats image
  game-core/src/main/java/games/strategy/triplea/ui/BattleDisplay.java
  game-core/src/main/java/games/strategy/triplea/ui/HeadedUiContext.java
  game-core/src/main/java/games/strategy/triplea/ui/HeadlessUiContext.java
  game-core/src/main/java/games/strategy/triplea/ui/IndividualUnitPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/StatPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/UiContext.java
Labels: PR: <BUILD PASSED>

#3081 Equals() call on enum -> '=='
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/TimespanDialog.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleTracker.java
  game-core/src/main/java/games/strategy/triplea/delegate/dataObjects/BattleRecord.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
Labels: PR: <BUILD PASSED>

#3080 String.equals("") -> isEmpty()
  game-core/src/main/java/games/strategy/engine/data/export/GameDataExporter.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
  game-core/src/main/java/games/strategy/triplea/printgenerator/SetupFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/MapRouteDrawer.java
  game-core/src/main/java/games/strategy/triplea/ui/TooltipProperties.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/history/HistoryLog.java
  game-core/src/main/java/tools/image/ReliefImageBreaker.java
Labels: PR: <BUILD PASSED>

#3082 Simplify boolean expressions
  game-core/src/main/java/games/strategy/engine/data/Unit.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/ProTechAi.java
  game-core/src/main/java/games/strategy/triplea/ui/history/HistoryPanel.java
Labels: PR: <BUILD PASSED>

#3077 Fix string concatenation argument to string builder
  game-core/src/main/java/games/strategy/engine/lobby/server/ModeratorController.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ExportMenu.java
Labels: PR: <BUILD PASSED>

#3056 Remove more unused
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPlaceTerritory.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPurchaseOptionMap.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProTerritory.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProTerritoryManager.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/simulate/ProDummyDelegateBridge.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/util/ProMatches.java
  game-core/src/main/java/games/strategy/triplea/ui/ActionButtons.java
  game-core/src/main/java/games/strategy/triplea/ui/IndividualUnitPanelGrouped.java
  game-core/src/main/java/games/strategy/triplea/ui/JButtonDialog.java
Labels: PR: <BUILD PASSED>

#3073 Update getLauncher to return optional
  game-core/src/main/java/games/strategy/engine/framework/headlessGameServer/HeadlessGameServer.java
  game-core/src/main/java/games/strategy/engine/framework/headlessGameServer/HeadlessServerSetup.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ISetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/LocalSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/MainPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/PbemSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/SetupPanel.java
  game-core/src/main/java/org/triplea/client/launch/screens/LaunchScreenWindow.java
Labels: PR: <BUILD PASSED>

#3097 IDE fix: Replace variables with known constants
  game-core/src/main/java/games/strategy/triplea/attachments/RulesAttachment.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractPlaceDelegate.java
  game-core/src/main/java/games/strategy/ui/IntTextField.java
Labels: PR: <BUILD PASSED>

#3046 Add Lombok (Lombok Spike)
  docs/dev/README.md
  game-core/build.gradle
  game-core/src/main/java/games/strategy/engine/framework/VerifiedRandomNumbers.java
  game-core/src/main/java/games/strategy/engine/gamePlayer/DefaultPlayerBridge.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProBattleResult.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProMyMoveOptions.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPlaceTerritory.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPurchaseOption.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProPurchaseTerritory.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/data/ProTransport.java
  game-core/src/main/java/games/strategy/triplea/delegate/dataObjects/FightBattleDetails.java
  game-core/src/main/java/games/strategy/triplea/image/BlendComposite.java
  game-core/src/main/java/games/strategy/triplea/oddsCalculator/ta/AggregateResults.java
  game-core/src/main/java/games/strategy/triplea/oddsCalculator/ta/BattleResults.java
  game-core/src/main/java/games/strategy/triplea/player/AbstractBasePlayer.java
  game-core/src/main/java/games/strategy/triplea/ui/BattlePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MapRouteDrawer.java
  game-core/src/main/java/games/strategy/triplea/ui/logic/RouteCalculator.java
  game-core/src/test/java/games/strategy/triplea/ui/logic/RouteCalculatorTest.java
Labels: PR: <BUILD PASSED>

#3133 Remove always false boolean condition
  game-core/src/main/java/games/strategy/triplea/delegate/EditDelegate.java
Labels: PR: <BUILD PASSED>

#3153 Replace loop with Collection.removeIf
  game-core/src/main/java/games/strategy/engine/data/GameParser.java
  game-core/src/main/java/games/strategy/thread/LockUtil.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/ProNonCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/ProPurchaseAi.java
  game-core/src/main/java/games/strategy/triplea/ai/proAI/util/ProUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/weakAI/Utils.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleCalculator.java
  game-core/src/main/java/games/strategy/triplea/delegate/StrategicBombingRaidBattle.java
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PoliticalStateOverview.java
Labels: PR: <BUILD PASSED>

#3152 Replace loop with Arrays.setAll
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ExportMenu.java
Labels: PR: <BUILD PASSED>

#3143 Change test to mock mapper Function instead of IntegerMap
  game-core/src/main/java/games/strategy/util/IntegerMap.java
  game-core/src/test/java/games/strategy/triplea/attachments/TechAbilityAttachmentTest.java
Labels: PR: <BUILD PASSED>

#3148 Anonymous type can be replaced by lambda
  game-core/src/integ_test/java/games/strategy/engine/lobby/server/ModeratorControllerIntegrationTest.java
  game-core/src/integ_test/java/games/strategy/net/MessengerIntegrationTest.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadController.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/PbemSetupPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/tools/image/DecorationPlacer.java
  game-core/src/main/java/tools/image/PolygonGrabber.java
  game-core/src/main/java/tools/map/making/PlacementPicker.java
Labels: PR: <BUILD PASSED>

#3146 Simplify ClientProps getters/setters with lombok
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
Labels: PR: <BUILD PASSED>

#3171 Add separate case for adding just territory name if null attachment
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
Labels: PR: <BUILD PASSED>

#3167 Minor enhancements
  game-core/src/main/java/games/strategy/engine/data/TechnologyFrontier.java
  game-core/src/main/java/games/strategy/engine/framework/LocalPlayers.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/net/MacFinder.java
  game-core/src/main/java/games/strategy/triplea/delegate/AAInMoveUtil.java
  game-core/src/main/java/games/strategy/triplea/ui/StatPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
Labels: PR: <BUILD PASSED>, PR:<CONFLICT>
