Repository triplea-game/triplea, pull requests merged in 2019-09, with the labels that each got.

#5160 Fix lock map not working bug
  game-core/src/main/java/games/strategy/triplea/settings/BooleanClientSetting.java
Labels: PR: Problem Fix

#5161 Fix refactor bug that disabled sound on headed clients
  game-core/src/main/java/games/strategy/sound/ClipPlayer.java
Labels: PR: Problem Fix

#5159 Travis build stages / Parallel Builds
  .travis.yml
  .travis/do_release
  .travis/install
  .travis/launch_http_server
  .travis/setup_database
Labels: PR: Configuration Update

#5150 Lobby login validator refactor
  game-core/src/main/java/org/triplea/lobby/common/login/RsaAuthenticator.java
  game-core/src/test/java/org/triplea/lobby/common/login/RsaAuthenticatorTest.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/login/AllowCreateUserRules.java
  lobby/src/main/java/org/triplea/lobby/server/login/AllowLoginRules.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidatorFactory.java
  lobby/src/test/java/org/triplea/lobby/server/login/AllowCreateUserRulesTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
Labels: PR: Refactor

#5167 Restore Travis Deploy Step & Skip Install Step
  .travis.yml
Labels: PR: Configuration Update, PR: Problem Fix

#5172 Alpha-sort sounds path variables
  game-core/src/main/java/games/strategy/sound/SoundPath.java
Labels: PR: Refactor

#5173 Remove noisy log message
  game-core/src/main/java/games/strategy/net/nio/SocketReadData.java
Labels: PR: Problem Fix

#5174 Fix name assignment de-duper matching against bot names
  game-core/src/main/java/games/strategy/net/PlayerNameAssigner.java
  game-core/src/test/java/games/strategy/net/PlayerNameAssignerTest.java
Labels: PR: Problem Fix

#5185 Hide lobby client messengers & Refactor LobbyGameTableModel
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/GameListModel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
  game-core/src/main/java/org/triplea/lobby/common/GameDescription.java
  game-core/src/test/java/games/strategy/engine/lobby/client/ui/GameListModelTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModelTest.java
  game-core/src/test/java/org/triplea/lobby/common/GameDescriptionTest.java
  swing-lib/src/main/java/org/triplea/swing/MouseListenerBuilder.java
  swing-lib/src/test/java/org/triplea/swing/MouseListenerBuilderTest.java
Labels: PR: Refactor

#5188 Fix lobby menu & Use Menu Builder
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
Labels: PR: Problem Fix, PR: Refactor

#5189 Simplify the PR template, add an 'other' category.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Configuration Update

#5191 Remove java-sockets sub-project shell
  java-sockets/build.gradle
  settings.gradle
Labels: PR: Configuration Update

#5202 Update Travis on-failure script to not fire for PR builds for branches hosted from the main repo
  .travis.yml
Labels: PR: Configuration Update

#5203 Refactor: LobbyClient use immutable values over cached
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
Labels: PR: Refactor

#5210 Add a stalebot config, close issues after 120 days, PRs after 3 weeks.
  .github/stale.yml
Labels: PR: Configuration Update

#5219 Add "Impact: Incorrect UI Behavior" label to stalebot exclusion label
  .github/stale.yml
Labels: PR: Configuration Update

#5222 Update Issue Templates: Send Feature Requests to Forums
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: PR: Configuration Update

#5223 Update Bug Report Template to have a bug image
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: PR: Configuration Update

#5225 Squash changesets together
  lobby-db/src/main/resources/db/migration/V1.00.00__lobby.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190313.1200__delete_mute_by_username.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190320__drop_mutes.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190330__lobby_user_table.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190527__error_reporting_record.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190610__moderator_toolbox_support.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190812__temp_password.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190815__temp_password_audit.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190913__api_key.sql
  lobby-db/src/main/resources/db/migration/V1.10.00__lobby.sql
  lobby-db/src/main/resources/db/migration/V2.00.00__lobby.sql
Labels: PR: Configuration Update

#5230 Update label name in Build monitoring script
  .travis/report_build_status
Labels: PR: Configuration Update

#5231 Fix sample_data.sql script to remove table with FKs to lobby_user
  lobby-db/sample_data.sql
Labels: PR: Problem Fix

#5235 Db simplify
  lobby-db/src/main/resources/db/migration/V2.00.00__lobby.sql
Labels: PR: Configuration Update

#5243 Update Issue templates, combine code discussion and project discussion
  .github/ISSUE_TEMPLATE/code_design_discussion.md
  .github/ISSUE_TEMPLATE/project_discussion.md
Labels: PR: Configuration Update

#5236 Refactor: SwingBuilder API
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ConfirmationDialogController.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportSwingView.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadProgressPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/MetaSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/game/selector/GameSelectorPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/TimespanDialog.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/ToolBoxWindow.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/ShowApiKeyDialog.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/access/log/AccessLogTab.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/access/log/AccessLogTabActions.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/bad/words/BadWordsTab.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/banned/names/BannedUsernamesTab.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/banned/users/BannedUsersTab.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/event/log/EventLogTab.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/moderators/ModeratorsTab.java
  game-core/src/main/java/games/strategy/engine/pbem/ForumPosterComponent.java
  game-core/src/main/java/games/strategy/triplea/printgenerator/SetupFrame.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponentFactory.java
  game-core/src/main/java/games/strategy/triplea/settings/SettingsWindow.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/BattlePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/FindTerritoryDialog.java
  game-core/src/main/java/games/strategy/triplea/ui/PlayersPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PoliticsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PurchasePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/RepairPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TabbedProductionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TechPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/GameMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
  swing-lib/src/main/java/org/triplea/swing/JButtonBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/GridBagConstraintsAnchor.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/GridBagConstraintsBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/GridBagConstraintsFill.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/GridBagHelper.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/JPanelBuilder.java
  swing-lib/src/test/java/org/triplea/swing/JButtonBuilderTest.java
  swing-lib/src/test/java/org/triplea/swing/jpanel/GridBagHelperTest.java
  swing-lib/src/test/java/org/triplea/swing/jpanel/JPanelBuilderTest.java
Labels: PR: Refactor

#5241 Refactor: Replace GUID with built-in UUID
  game-core/src/main/java/games/strategy/engine/data/Unit.java
  game-core/src/main/java/games/strategy/engine/data/UnitsList.java
  game-core/src/main/java/games/strategy/engine/data/changefactory/PlayerOwnerChange.java
  game-core/src/main/java/games/strategy/engine/display/IDisplay.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/GameListModel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
  game-core/src/main/java/games/strategy/engine/message/HubInvocationResults.java
  game-core/src/main/java/games/strategy/engine/message/HubInvoke.java
  game-core/src/main/java/games/strategy/engine/message/InvocationInProgress.java
  game-core/src/main/java/games/strategy/engine/message/SpokeInvocationResults.java
  game-core/src/main/java/games/strategy/engine/message/SpokeInvoke.java
  game-core/src/main/java/games/strategy/engine/message/UnifiedMessengerHub.java
  game-core/src/main/java/games/strategy/engine/message/unifiedmessenger/InvocationResults.java
  game-core/src/main/java/games/strategy/engine/message/unifiedmessenger/Invoke.java
  game-core/src/main/java/games/strategy/engine/message/unifiedmessenger/UnifiedMessenger.java
  game-core/src/main/java/games/strategy/engine/player/Player.java
  game-core/src/main/java/games/strategy/net/GUID.java
  game-core/src/main/java/games/strategy/triplea/TripleAPlayer.java
  game-core/src/main/java/games/strategy/triplea/ai/AbstractAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProRetreatAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/AirBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleCalculator.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleTracker.java
  game-core/src/main/java/games/strategy/triplea/delegate/Fire.java
  game-core/src/main/java/games/strategy/triplea/delegate/FireAa.java
  game-core/src/main/java/games/strategy/triplea/delegate/IBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/data/BattleRecords.java
  game-core/src/main/java/games/strategy/triplea/odds/calculator/DummyPlayer.java
  game-core/src/main/java/games/strategy/triplea/ui/BattlePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/ObjectiveDummyDelegateBridge.java
  game-core/src/main/java/games/strategy/triplea/ui/display/HeadlessDisplay.java
  game-core/src/main/java/games/strategy/triplea/ui/display/TripleADisplay.java
  game-core/src/main/java/org/triplea/lobby/common/ILobbyGameBroadcaster.java
  game-core/src/main/java/org/triplea/lobby/common/ILobbyGameController.java
  game-core/src/test/java/games/strategy/engine/lobby/client/ui/GameListModelTest.java
  game-core/src/test/java/games/strategy/net/GuidTest.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyGameController.java
Labels: PR: Refactor

#5234 Add territory effect movement cost
  game-core/src/main/java/games/strategy/engine/data/CompositeRouteFinder.java
  game-core/src/main/java/games/strategy/engine/data/DefaultAttachment.java
  game-core/src/main/java/games/strategy/engine/data/GameMap.java
  game-core/src/main/java/games/strategy/engine/data/Route.java
  game-core/src/main/java/games/strategy/engine/data/RouteFinder.java
  game-core/src/main/java/games/strategy/engine/data/RouteScripted.java
  game-core/src/main/java/games/strategy/engine/data/changefactory/ChangeFactory.java
  game-core/src/main/java/games/strategy/performance/PerfTimer.java
  game-core/src/main/java/games/strategy/triplea/Constants.java
  game-core/src/main/java/games/strategy/triplea/Properties.java
  game-core/src/main/java/games/strategy/triplea/TripleAUnit.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProNonCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProPurchaseAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProTechAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/data/ProTerritoryManager.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProBattleUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProMatches.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProMoveUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProTerritoryValueUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProTransportUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/weak/Utils.java
  game-core/src/main/java/games/strategy/triplea/ai/weak/WeakAi.java
  game-core/src/main/java/games/strategy/triplea/attachments/TerritoryEffectAttachment.java
  game-core/src/main/java/games/strategy/triplea/delegate/AirMovementValidator.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/Matches.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/MovePerformer.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveValidator.java
  game-core/src/main/java/games/strategy/triplea/delegate/MustFightBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/RocketsFireHelper.java
  game-core/src/main/java/games/strategy/triplea/delegate/TerritoryEffectHelper.java
  game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/UnitChooser.java
  game-core/src/main/java/games/strategy/triplea/util/TransportUtils.java
  game-core/src/main/java/games/strategy/triplea/util/UnitCategory.java
  game-core/src/main/java/games/strategy/triplea/util/UnitSeparator.java
  game-core/src/test/java/games/strategy/engine/data/GameMapTest.java
  game-core/src/test/java/games/strategy/engine/data/MapTest.java
  game-core/src/test/java/games/strategy/engine/data/RouteFinderTest.java
  game-core/src/test/java/games/strategy/engine/data/RouteTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/AirThatCantLandUtilTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/BattleCalculatorTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/DiceRollTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/GameDataTestUtil.java
  game-core/src/test/java/games/strategy/triplea/delegate/LhtrTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveDelegateTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveValidatorTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/PacificTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/RevisedTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/TerritoryEffectHelperTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/VictoryTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year42Test.java
  game-core/src/test/java/games/strategy/triplea/ui/RouteDescriptionTest.java
  game-core/src/test/resources/Total_World_War_Dec1941.xml
Labels: PR: Feature Add

#5238 Refactor RoleAuthorizer
  http-server/src/main/java/org/triplea/server/access/AuthenticatedUser.java
  http-server/src/main/java/org/triplea/server/access/RoleAuthorizer.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/bad/words/BadWordsController.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/banned/names/UsernameBanController.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/banned/users/UserBanController.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsController.java
  http-server/src/test/java/org/triplea/server/access/AuthenticatedUserTest.java
  http-server/src/test/java/org/triplea/server/access/RoleAuthorizerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsControllerTest.java
Labels: PR: Refactor

#5257 Convert JPanelBuilder to a type-safe builder
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/BorderLayoutBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/BoxLayoutBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/FlowLayoutBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/GridBagLayoutBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/GridLayoutBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/JPanelBuilder.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/SimpleGridBagLayoutBuilder.java
  swing-lib/src/test/java/org/triplea/swing/jpanel/JPanelBuilderTest.java
  swing-lib/src/test/java/org/triplea/swing/jpanel/SimpleGridBagLayoutBuilderTest.java
Labels: PR: More to Follow, PR: Refactor

#5258 Replace ToolboxHttpHeaders with AuthenticationHeaders
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/ToolboxHttpHeaders.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/access/log/ToolboxAccessLogClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/bad/words/ToolboxBadWordsClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/banned/name/ToolboxUsernameBanClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/banned/user/ToolboxUserBanClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/event/log/ToolboxEventLogClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/moderator/management/ToolboxModeratorManagementClient.java
  http-clients/src/test/java/org/triplea/http/client/HttpClientTesting.java
  http-clients/src/test/java/org/triplea/http/client/moderator/toolbox/access/log/ToolboxAccessLogClientTest.java
  http-clients/src/test/java/org/triplea/http/client/moderator/toolbox/bad/words/ToolboxBadWordsClientTest.java
  http-clients/src/test/java/org/triplea/http/client/moderator/toolbox/banned/name/ToolboxUsernameBanClientTest.java
  http-clients/src/test/java/org/triplea/http/client/moderator/toolbox/banned/user/ToolboxUserBanClientTest.java
  http-clients/src/test/java/org/triplea/http/client/moderator/toolbox/event/log/ToolboxEventLogClientTest.java
  http-clients/src/test/java/org/triplea/http/client/moderator/toolbox/moderator/management/ToolboxModeratorManagementClientTest.java
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
Labels: PR: Refactor

#5260 Cleanup: HTTP Client consolidate header annotation
  http-clients/src/main/java/org/triplea/http/client/error/report/ErrorUploadClient.java
  http-clients/src/main/java/org/triplea/http/client/forgot/password/ForgotPasswordClient.java
  http-clients/src/main/java/org/triplea/http/client/github/issues/GithubClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/login/LobbyLoginClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/user/account/UserAccountFeignClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/access/log/ToolboxAccessLogFeignClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/bad/words/ToolboxBadWordsFeignClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/banned/name/ToolboxUsernameBanFeignClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/banned/user/ToolboxUserBanFeignClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/event/log/ToolboxEventLogFeignClient.java
  http-clients/src/main/java/org/triplea/http/client/moderator/toolbox/moderator/management/ToolboxModeratorManagementFeignClient.java
Labels: PR: Refactor

#5261 Cleanup: use 'getUserIdOrThrow' api
  http-server/src/main/java/org/triplea/server/user/account/UserAccountController.java
  http-server/src/test/java/org/triplea/server/user/account/UserAccountControllerTest.java
Labels: PR: Refactor

#5269 Upgrade Install4j to Install4j8
  .travis/do_release
  game-headed/build.gradle
  game-headed/build.install4j
Labels: PR: Configuration Update

#5268 Fix chat dialog not disappearing
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
Labels: PR: Problem Fix

#5266 Remove "me" messages & unused method 'speakerTagUpdated'
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessage.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPlayerPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/chat/IChatChannel.java
  game-core/src/main/java/games/strategy/engine/chat/IChatListener.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  game-headless/src/main/java/org/triplea/game/server/debug/ChatHandler.java
Labels: PR: Feature Removal, PR: More to Follow

#5267 Wire Https Port to Server Games
  .travis/run_smoke_tests
  game-core/src/main/java/games/strategy/engine/framework/CliProperties.java
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/IMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/Messengers.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
Labels: PR: More to Follow

#5270 Ai fix bugs
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/TerritoryEffectHelper.java
  game-core/src/test/java/games/strategy/triplea/delegate/TerritoryEffectHelperTest.java
Labels: PR: Problem Fix

#5265 Refactor: Simplify GameListing
  http-clients/src/main/java/org/triplea/http/client/lobby/game/listing/LobbyGameListing.java
  http-server/src/main/java/org/triplea/server/access/ApiKey.java
  http-server/src/main/java/org/triplea/server/access/ApiKeyAuthenticator.java
  http-server/src/main/java/org/triplea/server/access/AuthenticatedUser.java
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameListing.java
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameListingControllerFactory.java
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameReaper.java
  http-server/src/test/java/org/triplea/server/lobby/game/listing/GameListingTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/listing/GameReaperTest.java
Labels: PR: More to Follow, PR: Refactor

#5273 Fix headless launchers to have https port
  .idea/runConfigurations/HeadlessGameRunner.xml
  game-headless/.eclipse/HeadlessGameRunner.launch
Labels: PR: Configuration Update, PR: Problem Fix

#5276 Refactor: simplify game-selector-model
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/game/selector/GameSelectorPanel.java
  game-core/src/test/java/games/strategy/engine/framework/startup/mc/GameSelectorModelTest.java
Labels: PR: Refactor

#5271 Login UX & Remember Password Updates
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/SetupPanelModel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/ChangePasswordPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/CreateUpdateAccountPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLoginPreferences.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LoginPanel.java
  game-core/src/main/java/games/strategy/triplea/settings/BooleanClientSetting.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/games/strategy/ui/Util.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyLoginPreferencesTest.java
  swing-lib/src/main/java/org/triplea/swing/JCheckBoxBuilder.java
  swing-lib/src/main/java/org/triplea/swing/JMenuItemCheckBoxBuilder.java
  swing-lib/src/main/java/org/triplea/swing/JTextFieldBuilder.java
  swing-lib/src/main/java/org/triplea/swing/SettingPersistence.java
  swing-lib/src/test/java/org/triplea/swing/JCheckBoxBuilderTest.java
Labels: PR: Feature Update, PR: More to Follow

#5277 Refactor: Use '@Getter' in PlayerListing
  game-core/src/main/java/games/strategy/engine/framework/message/PlayerListing.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
Labels: PR: Refactor

#5278 Remove moderator controller info logging
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
Labels: PR: More to Follow, PR: Refactor

#5274 Chat panel refactor & lobby menu show chat time persisted
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
  game-core/src/main/java/org/triplea/game/chat/ChatModel.java
Labels: PR: Feature Update, PR: More to Follow, PR: Refactor

#5280 Refactor: Convert 'String' to value object 'PlayerName'
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatFloodControl.java
  game-core/src/main/java/games/strategy/engine/chat/ChatIgnoreList.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessage.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPlayerPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/chat/IChatChannel.java
  game-core/src/main/java/games/strategy/engine/chat/IChatListener.java
  game-core/src/main/java/games/strategy/engine/framework/ClientGame.java
  game-core/src/main/java/games/strategy/engine/framework/network/ui/BanPlayerAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/PlayerName.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/net/INode.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/lobby/common/IUserManager.java
  game-core/src/test/java/games/strategy/engine/chat/ChatFloodControlTest.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIgnoreListTest.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/UserManager.java
  lobby/src/test/java/org/triplea/lobby/server/ModeratorControllerIntegrationTest.java
Labels: PR: Refactor

#5281 Refactor: Simplify LobbyWatcher
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/LocalServerAvailabilityCheck.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/engine/message/IRemoteMessenger.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
  game-core/src/main/java/org/triplea/lobby/common/ILobbyGameController.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyGameController.java
Labels: PR: Refactor

#5285 Fix: Headless bot select player option
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
Labels: PR: Problem Fix

#5299 Simplify Headless chat
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
Labels: PR: Refactor

#5300 Refactor: Remove Observable from SetupModel
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/SetupPanel.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
  game-core/src/main/java/org/triplea/game/startup/SetupModel.java
Labels: PR: Refactor

#5301 Refactor: Fix variable shadowing in test
  game-core/src/test/java/games/strategy/triplea/delegate/TerritoryEffectHelperTest.java
Labels: PR: Refactor

#5298 Refactor: Api-key consolidation and validation
  game-core/src/main/java/games/strategy/engine/lobby/ApiKey.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/IClientMessenger.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ClientQuarantineConversation.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  http-clients/src/main/java/org/triplea/http/client/ApiKey.java
  http-clients/src/main/java/org/triplea/http/client/AuthenticationHeaders.java
  http-clients/src/main/java/org/triplea/http/client/lobby/HttpLobbyClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/listing/GameListingClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/HttpModeratorToolboxClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/NewApiKey.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/banned/name/ToolboxUsernameBanClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/banned/user/ToolboxUserBanClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/log/ToolboxAccessLogClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/log/ToolboxEventLogClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/management/ToolboxModeratorManagementClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/toolbox/words/ToolboxBadWordsClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/user/account/UserAccountClient.java
  http-clients/src/test/java/org/triplea/http/client/HttpClientTesting.java
  http-clients/src/test/java/org/triplea/http/client/WireMockTest.java
  http-clients/src/test/java/org/triplea/http/client/error/report/ErrorReportClientTest.java
  http-clients/src/test/java/org/triplea/http/client/forgot/password/ForgotPasswordClientTest.java
  http-clients/src/test/java/org/triplea/http/client/github/issues/GithubIssueClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/game/listing/GameListingClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/login/LobbyLoginClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/toolbox/banned/name/ToolboxUsernameBanClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/toolbox/banned/user/ToolboxUserBanClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/toolbox/log/ToolboxAccessLogClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/toolbox/log/ToolboxEventLogClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/toolbox/management/ToolboxModeratorManagementClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/toolbox/words/ToolboxBadWordsClientTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/user/account/UserAccountClientTest.java
  http-server/src/main/java/org/triplea/server/access/ApiKey.java
  http-server/src/main/java/org/triplea/server/access/ApiKeyAuthenticator.java
  http-server/src/main/java/org/triplea/server/access/AuthenticatedUser.java
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameListing.java
  http-server/src/test/java/org/triplea/server/http/ProtectedEndpointTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/listing/GameListingTest.java
  lobby/build.gradle
  lobby/src/main/java/org/triplea/lobby/server/api/key/ApiKeyGenerator.java
  lobby/src/main/java/org/triplea/lobby/server/api/key/ApiKeyGeneratorFactory.java
  lobby/src/test/java/org/triplea/lobby/server/api/key/ApiKeyGeneratorTest.java
Labels: PR: More to Follow, PR: Refactor

#5305 Refactor: simplify always true null check condition
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java
Labels: PR: Refactor

#5306 Refactor: Remove deprecated Observable from ImageScrollModel
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/ui/ImageScrollModel.java
  game-core/src/main/java/games/strategy/ui/ImageScrollerLargeView.java
  game-core/src/main/java/games/strategy/ui/ImageScrollerSmallView.java
Labels: PR: Refactor

#5304 Refactor: Move connectivity check to http
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/LocalServerAvailabilityCheck.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/net/INode.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
  game-core/src/main/java/org/triplea/lobby/common/ILobbyGameController.java
  game-core/src/test/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcherTest.java
  http-clients/src/main/java/org/triplea/http/client/lobby/HttpLobbyClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/ConnectivityCheckClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/ConnectivityCheckFeignClient.java
  http-clients/src/test/java/org/triplea/http/client/lobby/game/ConnectivityCheckClientTest.java
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
  http-server/src/main/java/org/triplea/server/lobby/game/ConnectivityCheck.java
  http-server/src/main/java/org/triplea/server/lobby/game/ConnectivityController.java
  http-server/src/main/java/org/triplea/server/lobby/game/ConnectivityControllerFactory.java
  http-server/src/test/java/org/triplea/server/lobby/game/ConnectivityCheckTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/ConnectivityControllerTest.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyGameController.java
Labels: PR: Refactor

#5294 ChatModel simplification
  game-core/src/main/java/games/strategy/engine/chat/ChatPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
  game-core/src/main/java/org/triplea/game/chat/ChatModel.java
Labels: PR: Refactor
