Repository triplea-game/triplea, pull requests merged in 2019-01, with the labels that each got.

#4454 Refactor PbF/PbEM Poster code
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ISetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/LocalSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/MetaSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/PbemSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/SetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/DiceServerEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/DisplayNameComboBoxRender.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/EditorPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/EmailSenderEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/ForumPosterEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/IBean.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/SelectAndViewEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/validators/EmailValidator.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/validators/IValidator.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/validators/IntegerRangeValidator.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/validators/NonEmptyValidator.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanelBuilder.java
  game-core/src/main/java/games/strategy/engine/pbem/AbstractForumPoster.java
  game-core/src/main/java/games/strategy/engine/pbem/AxisAndAlliesForumPoster.java
  game-core/src/main/java/games/strategy/engine/pbem/DefaultEmailSender.java
  game-core/src/main/java/games/strategy/engine/pbem/ForumPosterComponent.java
  game-core/src/main/java/games/strategy/engine/pbem/GenericEmailSender.java
  game-core/src/main/java/games/strategy/engine/pbem/GmailEmailSender.java
  game-core/src/main/java/games/strategy/engine/pbem/HotmailEmailSender.java
  game-core/src/main/java/games/strategy/engine/pbem/IEmailSender.java
  game-core/src/main/java/games/strategy/engine/pbem/IForumPoster.java
  game-core/src/main/java/games/strategy/engine/pbem/NodeBbForumPoster.java
  game-core/src/main/java/games/strategy/engine/pbem/PbemMessagePoster.java
  game-core/src/main/java/games/strategy/engine/pbem/TripleAForumPoster.java
  game-core/src/main/java/games/strategy/engine/random/IRemoteDiceServer.java
  game-core/src/main/java/games/strategy/engine/random/InternalDiceServer.java
  game-core/src/main/java/games/strategy/engine/random/PropertiesDiceRoller.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractEndTurnDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/remote/IAbstractForumPosterDelegate.java
  game-core/src/main/java/games/strategy/triplea/help/HelpSupport.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponentFactory.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractForumPosterPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/FileMenu.java
  game-core/src/main/java/games/strategy/util/Util.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
  game-core/src/main/resources/games/strategy/triplea/help/axisAndAlliesForum.html
  game-core/src/main/resources/games/strategy/triplea/help/emailSenders.html
  game-core/src/main/resources/games/strategy/triplea/help/forumPosters.html
  game-core/src/main/resources/games/strategy/triplea/help/genericEmailSender.html
  game-core/src/main/resources/games/strategy/triplea/help/gmailEmailSender.html
  game-core/src/main/resources/games/strategy/triplea/help/hotmailEmailSender.html
  game-core/src/main/resources/games/strategy/triplea/help/tripleaForum.html
  game-core/src/test/java/games/strategy/engine/framework/startup/ui/ISetupPanelTest.java
  game-core/src/test/java/games/strategy/engine/pbem/AbstractForumPosterTest.java
  game-core/src/test/java/games/strategy/engine/pbem/GenericEmailSenderTest.java
  game-core/src/test/java/games/strategy/engine/random/InternalDiceServerTest.java
  game-core/src/test/java/games/strategy/engine/random/PropertiesDiceRollerTest.java
  game-core/src/test/java/games/strategy/util/UtilTest.java
  game-headed/dice_servers/marti-staging.properties
  game-headed/dice_servers/marti.properties
Labels: category: code improvement

#4559 Docs: eclipse IDE setup instructions update
  docs/dev/setup/ide/eclipse.md
Labels: PR: Documentation

#4556 Docs: Edit/Shorten code-standards documentation
  docs/dev/conventions/code_standards.md
Labels: PR: Documentation

#4558 Docs: create legacy folder, move 'engine_code_overview.md'
  docs/dev/legacy/engine_code_overview.md
Labels: PR: Documentation-Only

#4579 Simple: Remove variable that is always null
  game-core/src/main/java/games/strategy/engine/data/changefactory/RemoveBattleRecordsChange.java
Labels: PR: Refactor

#4581 Refactor: Remove unnecessary method overrides
  game-core/src/main/java/games/strategy/triplea/delegate/BasePersistentDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/EditDelegate.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
Labels: PR: Refactor

#4582 Cleanup: Remove empty param javadoc and replace single character param name
  game-core/src/main/java/games/strategy/triplea/delegate/TechAdvance.java
Labels: PR: Refactor

#4584 Simplifications: remove unnecessary toString and semi's
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/logging/ProLogWindow.java
  game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponent.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/GameMenu.java
Labels: PR: Refactor

#4585 Simple: inline variable and convert switch to if
  game-core/src/main/java/games/strategy/triplea/ui/FindTerritoryDialog.java
  game-core/src/main/java/swinglib/JLabelBuilder.java
Labels: PR: Refactor

#4587 Replace getters in Territory.java with lombok `@Getter`
  game-core/src/main/java/games/strategy/engine/data/Territory.java
Labels: PR: Refactor

#4583 Remove always false condition
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProTechAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/TransportTracker.java
Labels: PR: Refactor

#4580 Simplify always true conditionals
  game-core/src/main/java/games/strategy/engine/data/UnitCollection.java
  game-core/src/main/java/games/strategy/triplea/attachments/TriggerAttachment.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractPlaceDelegate.java
  game-core/src/main/java/games/strategy/triplea/ui/ProductionRepairPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/history/HistoryLog.java
Labels: PR: Refactor

#4586 Refactor: Convert methods with unused return value to void
  game-core/src/main/java/games/strategy/engine/ClientContext.java
  game-core/src/main/java/games/strategy/engine/auto/update/TutorialMapCheck.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadController.java
  game-core/src/main/java/games/strategy/engine/framework/system/SystemProperties.java
  game-core/src/main/java/games/strategy/engine/framework/ui/DefaultGameChooserEntry.java
  game-core/src/main/java/games/strategy/engine/framework/ui/GameChooserEntry.java
  game-core/src/main/java/games/strategy/engine/framework/ui/GameChooserModel.java
  game-core/src/main/java/games/strategy/sound/ClipPlayer.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProPurchaseAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/AaInMoveUtil.java
  game-core/src/main/java/games/strategy/triplea/delegate/BaseEditDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/data/MoveValidationResult.java
  game-core/src/main/java/games/strategy/triplea/delegate/remote/IEditDelegate.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponentFactory.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/history/HistoryPanel.java
  game-core/src/main/java/games/strategy/ui/SwingComponents.java
  game-core/src/main/java/swinglib/JTextFieldBuilder.java
  game-core/src/test/java/games/strategy/engine/ClientContextIntegrationTest.java
Labels: PR: Refactor

#4598 Cleanup: Replace redundant add all call with parameterized constructor
  game-core/src/test/java/games/strategy/triplea/delegate/MoveDelegateTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  game-core/src/test/java/games/strategy/triplea/util/UnitSeparatorTest.java
  game-core/src/test/java/org/triplea/lobby/common/login/RsaAuthenticatorTest.java
Labels: PR: Cleanup

#4600 Cleanup: Replace empty and single Arrays.asList
  game-core/src/test/java/games/strategy/engine/framework/map/download/MapDownloadListTest.java
  game-core/src/test/java/games/strategy/triplea/attachments/TriggerAttachmentTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  game-core/src/test/java/games/strategy/util/CollectionUtilsTest.java
  game-core/src/test/java/games/strategy/util/OpenJsonUtilsTest.java
  game-core/src/test/java/games/strategy/util/PointFileReaderWriterTest.java
  game-core/src/test/java/games/strategy/util/UtilTest.java
Labels: PR: Cleanup

#4608 Simplify, remove "n" requests sent to "sourceforge", just send one network request
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionProperties.java
Labels: PR: Refactor

#4591 Improve SelectionComponent validation design
  game-core/src/main/java/games/strategy/triplea/settings/ClientSettingSwingUiBinding.java
  game-core/src/main/java/games/strategy/triplea/settings/SaveFunction.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponent.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponentFactory.java
  game-core/src/main/java/games/strategy/util/OptionalUtils.java
  game-core/src/test/java/games/strategy/triplea/settings/SaveFunctionTest.java
  game-core/src/test/java/games/strategy/util/OptionalUtilsTest.java
  game-headed/src/main/java/org/triplea/game/client/ui/javafx/SettingsPane.java
  game-headed/src/main/java/org/triplea/game/client/ui/javafx/util/JavaFxSelectionComponentFactory.java
Labels: PR: Refactor

#4615 Simplify never-null conditions and add assertions.
  game-core/src/main/java/games/strategy/engine/pbem/DefaultEmailSender.java
  game-core/src/main/java/games/strategy/engine/pbem/IEmailSender.java
Labels: PR: Cleanup

#4611 Simplify stream chains
  game-core/src/main/java/games/strategy/debug/LoggerManager.java
  game-core/src/test/java/games/strategy/net/IpFinderTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveValidatorTest.java
Labels: PR: Cleanup

#4602 Simplify/remove always false method
  game-core/src/main/java/games/strategy/engine/pbem/ForumPosterComponent.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractForumPosterPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/EndTurnPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MoveForumPosterPanel.java
Labels: PR: Cleanup

#4616 Script update: run-docker.sh restarts container
  lobby-db/run-docker.sh
Labels: PR: Dev Infrastructure

#4603 Do not show empty download maps window on internet errors.
  game-core/src/main/java/games/strategy/engine/ClientContext.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadRunnable.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadController.java
  game-core/src/test/java/games/strategy/engine/ClientContextIntegrationTest.java
Labels: PR: Feature Update

#4601 Update no internet error message to an info
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionProperties.java
Labels: PR: Feature Update

#4604 Simplify junit assertions
  game-core/src/test/java/games/strategy/triplea/delegate/PlaceDelegateTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/RevisedTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/VictoryTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year42Test.java
  game-core/src/test/java/games/strategy/triplea/util/WrappedInvocationHandlerTest.java
Labels: PR: Cleanup

#4590 Misc refactoring
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/ServerLauncher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/ui/ImageScrollerLargeView.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
Labels: PR: Cleanup

#4609 Remove a number of unused java elements.
  game-core/src/main/java/games/strategy/engine/data/RelationshipTracker.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/triplea/delegate/Matches.java
  game-core/src/main/java/games/strategy/triplea/ui/JButtonDialog.java
  game-core/src/main/java/games/strategy/triplea/ui/ResourceBar.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/swinglib/JButtonBuilder.java
  game-core/src/main/java/swinglib/JComboBoxBuilder.java
  game-core/src/main/java/swinglib/JLabelBuilder.java
  game-core/src/main/java/swinglib/JPanelBuilder.java
  game-core/src/main/java/swinglib/JTextAreaBuilder.java
  game-core/src/main/java/swinglib/JTextFieldBuilder.java
  game-core/src/main/java/swinglib/JTextFieldButtonAttachmentBuilder.java
  game-core/src/test/java/games/strategy/triplea/delegate/FakeTechAdvance.java
Labels: PR: Cleanup

#4624 Improved: Show territory effect image tooltip text
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
Labels: PR: Feature Update

#4622 Update "run-docker" script for lobby-db to clean terminated containers
  lobby-db/run-docker.sh
Labels: PR: Dev Infrastructure

#4626 Check-in an IDEA analysis configuration file
  config/IDEA_analysis_TripleA.xml
  docs/dev/setup/ide/intellij.md
Labels: PR: Dev Infrastructure

#4630 Refactor DownloadRunnable
  game-core/src/main/java/games/strategy/engine/ClientContext.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/ContentReader.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadRunnable.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadController.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyPropertyFetcherConfiguration.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParser.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcher.java
  game-core/src/test/java/games/strategy/engine/ClientContextIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/ContentReaderTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParserTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcherTest.java
Labels: PR: Cleanup

#4607 Display log level on log level button.
  game-core/src/main/java/games/strategy/debug/Console.java
  game-core/src/main/java/games/strategy/debug/DefaultConsole.java
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/debug/LoggerManager.java
  game-core/src/main/java/games/strategy/debug/console/window/ConsoleConfiguration.java
  game-core/src/main/java/games/strategy/debug/console/window/ConsoleHandler.java
  game-core/src/main/java/games/strategy/debug/console/window/ConsoleModel.java
  game-core/src/main/java/games/strategy/debug/console/window/ConsoleView.java
  game-core/src/main/java/games/strategy/debug/console/window/ConsoleWindow.java
  game-core/src/main/java/games/strategy/debug/console/window/DebugUtils.java
  game-core/src/main/java/games/strategy/ui/SystemClipboard.java
  game-core/src/main/java/swinglib/JComboBoxBuilder.java
  game-core/src/main/java/swinglib/JFrameBuilder.java
  game-core/src/main/java/swinglib/JTextAreaBuilder.java
  game-core/src/test/java/games/strategy/debug/console/window/ConsoleHandlerTest.java
  game-core/src/test/java/games/strategy/debug/console/window/ConsoleModelTest.java
  game-headed/src/main/java/org/triplea/game/client/HeadedGameRunner.java
Labels: PR: Feature Update, PR: Refactor
