Repository triplea-game/triplea, pull requests merged in 2019-08, with the labels that each got.

#4947 Remove parallel stream operation, does not improve performance
  game-core/src/main/java/games/strategy/net/PlayerNameAssigner.java
Labels: PR: Refactor

#4931 Decouple launcher code from UI
  game-core/src/main/java/games/strategy/engine/framework/AutoSaveFileUtils.java
  game-core/src/main/java/games/strategy/engine/framework/HeadlessAutoSaveFileUtils.java
  game-core/src/main/java/games/strategy/engine/framework/HeadlessAutoSaveType.java
  game-core/src/main/java/games/strategy/engine/framework/IGameLoader.java
  game-core/src/main/java/games/strategy/engine/framework/ServerGame.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/AbstractLauncher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/ILauncher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/LaunchAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/LauncherFactory.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/LocalLauncher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/ServerLauncher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/HeadedLaunchAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/SetupPanelModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/LocalSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/PbemSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanelBuilder.java
  game-core/src/main/java/games/strategy/triplea/TripleA.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetupPanelModel.java
  game-core/src/test/java/games/strategy/engine/framework/AutoSaveFileUtilsTest.java
  game-core/src/test/java/games/strategy/engine/framework/HeadlessAutoSaveFileUtilsTest.java
Labels: PR: Refactor

#4951 Update IDE setup documentation with notes for google-java-format
  docs/dev/ide-setup/eclipse.md
  docs/dev/ide-setup/intellij.md
Labels: PR: Documentation-Only

#4950 DBUser / Name+email validation refactor and validate name on server side
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/DiceServerEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/EmailSenderEditor.java
  game-core/src/main/java/games/strategy/engine/lobby/PlayerEmailValidation.java
  game-core/src/main/java/games/strategy/engine/lobby/PlayerNameValidation.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/CreateUpdateAccountPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LoginPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/server/userDB/DBUser.java
  game-core/src/main/java/games/strategy/net/PlayerNameAssigner.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/org/triplea/lobby/common/IUserManager.java
  game-core/src/test/java/games/strategy/engine/lobby/PlayerEmailValidationTest.java
  game-core/src/test/java/games/strategy/engine/lobby/PlayerNameValidationTest.java
  game-core/src/test/java/games/strategy/net/PlayerNameAssignerTest.java
  game-core/src/test/java/org/triplea/lobby/common/DbUserTest.java
  java-extras/src/main/java/org/triplea/java/StringUtils.java
  java-extras/src/test/java/org/triplea/java/StringUtilsTest.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/UserManager.java
  lobby/src/main/java/org/triplea/lobby/server/db/AccessLogController.java
  lobby/src/main/java/org/triplea/lobby/server/db/AccessLogDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/UserController.java
  lobby/src/main/java/org/triplea/lobby/server/db/UserDao.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/test/java/org/triplea/lobby/server/db/UserControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
Labels: PR: Feature Update, PR: Refactor

#4949 Dev documentation, updated IDE setup
  config/IDEA_analysis_TripleA.xml
  docs/dev/README.md
  docs/dev/build_installers.md
  docs/dev/contribution_guidelines.md
  docs/dev/conventions/code_standards.md
  docs/dev/conventions/communication.md
  docs/dev/conventions/lombok.md
  docs/dev/conventions/naming_conventions.md
  docs/dev/local_build_and_testing.md
  docs/dev/making_database_changes.md
  docs/dev/process/code_reviews.md
  docs/dev/setup/dev_setup.md
  docs/dev/setup/docker.md
  docs/dev/setup/ide/eclipse.md
  docs/dev/setup/ide/intellij.md
  docs/dev/updating_gradle.md
  docs/dev/versioning.md
Labels: PR: Documentation-Only

#4956 Simplify Unit.java, use lombok
  game-core/src/main/java/games/strategy/engine/data/Unit.java
Labels: PR: Refactor

#4961 Add: Lobby Login Throttle
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/login/FailedLoginThrottle.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/test/java/org/triplea/lobby/server/login/FailedLoginThrottleTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
Labels: PR: Feature Update

#4960 Add: Unit Scroller UI Feature
  .gitignore
  game-core/src/main/java/games/strategy/engine/data/GameData.java
  game-core/src/main/java/games/strategy/engine/data/GameDataEvent.java
  game-core/src/main/java/games/strategy/engine/data/GameDataEventListeners.java
  game-core/src/main/java/games/strategy/engine/data/GameStep.java
  game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java
  game-core/src/main/java/games/strategy/engine/data/changefactory/ObjectPropertyChange.java
  game-core/src/main/java/games/strategy/engine/data/changefactory/RemoveUnits.java
  game-core/src/main/java/games/strategy/engine/data/events/GameStepListener.java
  game-core/src/main/java/games/strategy/engine/framework/AbstractGame.java
  game-core/src/main/java/games/strategy/engine/framework/ClientGame.java
  game-core/src/main/java/games/strategy/engine/framework/IGame.java
  game-core/src/main/java/games/strategy/engine/framework/ServerGame.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/player/DefaultPlayerBridge.java
  game-core/src/main/java/games/strategy/triplea/delegate/GameStepPropertiesHelper.java
  game-core/src/main/java/games/strategy/triplea/delegate/Matches.java
  game-core/src/main/java/games/strategy/triplea/image/ImageLoader.java
  game-core/src/main/java/games/strategy/triplea/image/UnitImageFactory.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractUndoableMovesPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PlacePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/HelpMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/AvatarPanelFactory.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerIcon.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java
  game-headed/build.gradle
  swing-lib/src/main/java/org/triplea/swing/SwingComponents.java
Labels: PR: Feature Add

#4966 Move add/remove error listener from IMessenger to IClientMessenger
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/message/unifiedmessenger/UnifiedMessenger.java
  game-core/src/main/java/games/strategy/net/IClientMessenger.java
  game-core/src/main/java/games/strategy/net/IMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/Messengers.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/test/java/games/strategy/net/MessengerIntegrationTest.java
Labels: PR: Refactor

#4967 Refactor, minor simplify in EditPanel
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
Labels: PR: Refactor

#4968 Fix @Nullable annotation, will cause NPE if null and param is never null
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
Labels: PR: Refactor

#4969 Refactor, minor simplify to highlighted units collection usage
  game-core/src/main/java/games/strategy/triplea/ui/AbstractUndoableMovesPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Refactor

#4977 Refactor: use lombok getter+setter for lobbyLoginValidator property
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
Labels: PR: Refactor

#4980 Fix load sample data DB script
  lobby-db/load_sample_data
Labels: PR: Bug Fix

#4982 Fix potential NPE in LobbyGameController
  lobby/src/main/java/org/triplea/lobby/server/LobbyGameController.java
Labels: PR: Refactor

#4984 Refactor: Use lombok equalsAndHashCode (HashedPassword.java)
  lobby/src/main/java/org/triplea/lobby/server/db/HashedPassword.java
Labels: PR: Refactor

#4981 Add: Forgot Password DB Table and DAO
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/TempPasswordDao.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordDaoTest.java
  lobby-db-dao/src/test/resources/datasets/moderator_api_key/select.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/history-select.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/pre-insert.yml
  lobby-db-dao/src/test/resources/datasets/moderator_single_use_key/empty.yml
  lobby-db-dao/src/test/resources/datasets/moderator_single_use_key/select.yml
  lobby-db-dao/src/test/resources/datasets/moderators/select.yml
  lobby-db-dao/src/test/resources/datasets/temp_password/sample.yml
  lobby-db-dao/src/test/resources/datasets/user_lookup/select.yml
  lobby-db/src/main/resources/db/migration/V1.10.00.20190812__temp_password.sql
Labels: PR: Feature Add

#4985 Update: Allow user password update without updating email
  lobby/src/main/java/org/triplea/lobby/server/db/UserController.java
Labels: PR: Feature Update, PR: Refactor

#4979 Refactor: fix law of demeter violation in LobbyMenu
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
Labels: PR: Refactor

#4992 Refactor: update optional API usage
  game-core/src/main/java/org/triplea/game/server/AvailableGames.java
Labels: PR: Refactor

#4993 Refactor: replace not is present optional method with is empty
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/system/HttpProxy.java
  game-core/src/main/java/games/strategy/engine/framework/ui/DefaultGameChooserEntry.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/ShowToolboxController.java
  game-core/src/main/java/games/strategy/triplea/ResourceLoader.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProPurchaseAi.java
  game-core/src/main/java/games/strategy/triplea/attachments/UserActionAttachment.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveValidator.java
  game-core/src/main/java/games/strategy/triplea/image/UnitImageFactory.java
  game-core/src/main/java/games/strategy/triplea/ui/mapdata/MapData.java
  game-core/src/main/java/games/strategy/triplea/ui/screen/UnitsDrawer.java
  game-core/src/main/java/games/strategy/triplea/util/TransportUtils.java
  java-extras/src/main/java/org/triplea/java/OptionalUtils.java
Labels: PR: Refactor

#4994 Refactor: games.stratety.triplea reduce scope and use lombok
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractStatPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractUiContext.java
  game-core/src/main/java/games/strategy/triplea/ui/ActionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/BattleDisplay.java
  game-core/src/main/java/games/strategy/triplea/ui/BattleStepsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/HeadedUiContext.java
  game-core/src/main/java/games/strategy/triplea/ui/MouseDetails.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PickTerritoryAndUnitsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PlaceData.java
  game-core/src/main/java/games/strategy/triplea/ui/PlacePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PoliticsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PoliticsText.java
  game-core/src/main/java/games/strategy/triplea/ui/ProductionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/StatPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/UserActionText.java
Labels: PR: Refactor

#4995 Couple Automated Code Fixes (IDEA Analysis)
  game-core/src/main/java/games/strategy/engine/data/RelationshipTypeList.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadFileParser.java
  game-core/src/main/java/games/strategy/engine/message/unifiedmessenger/EndPoint.java
  game-core/src/main/java/games/strategy/triplea/TripleAPlayer.java
  game-core/src/main/java/games/strategy/triplea/ai/AbstractAi.java
  game-core/src/main/java/games/strategy/triplea/odds/calculator/OddsCalculatorDialog.java
  game-core/src/main/java/games/strategy/triplea/player/ITripleAPlayer.java
  game-core/src/test/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModelTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/AirThatCantLandUtilTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  http-clients/src/test/java/org/triplea/http/client/JsonEncoderTest.java
  http-server/src/main/java/org/triplea/server/http/AppConfig.java
  http-server/src/test/java/org/triplea/server/error/reporting/ErrorReportResponseAdapterTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/api/key/registration/ApiKeyRegistrationControllerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/api/key/validation/ValidKeyCacheTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/banned/users/BannedUsersControllerTest.java
  java-extras/src/main/java/org/triplea/java/Interruptibles.java
  swing-lib/src/main/java/org/triplea/swing/JPanelBuilder.java
  test-common/src/main/java/org/triplea/test/common/swing/SwingComponentWrapper.java
Labels: PR: Refactor

#4996 Non-deterministic Test Fix: delete table with FK
  lobby-db-dao/src/test/resources/datasets/temp_password/sample.yml
Labels: PR: Problem Fix

#4991 Add: Forgot Password Feature
  .idea/runConfigurations/LobbyRunner.xml
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/SetupPanelModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/ChangePasswordPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/ForgotPasswordPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LoginPanel.java
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/ClientMessengerFactory.java
  game-core/src/main/java/games/strategy/net/IClientMessenger.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/Messengers.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/TempPasswordHistory.java
  game-core/src/main/java/games/strategy/net/nio/ClientQuarantineConversation.java
  game-core/src/main/java/games/strategy/net/nio/ForgotPasswordConversation.java
  game-core/src/main/java/games/strategy/net/nio/NioSocket.java
  game-core/src/main/java/games/strategy/net/nio/NioSocketListener.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/main/java/org/triplea/lobby/common/login/LobbyLoginResponseKeys.java
  game-core/src/main/java/org/triplea/lobby/common/login/RsaAuthenticator.java
  game-core/src/test/java/games/strategy/net/nio/ForgotPasswordConversationTest.java
  game-core/src/test/java/org/triplea/lobby/common/login/RsaAuthenticatorTest.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/TempPasswordDao.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/TempPasswordHistoryDao.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordHistoryDaoTest.java
  lobby-db-dao/src/test/resources/datasets/moderator_api_key/select.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/history-select.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/pre-insert.yml
  lobby-db-dao/src/test/resources/datasets/moderator_single_use_key/empty.yml
  lobby-db-dao/src/test/resources/datasets/moderator_single_use_key/select.yml
  lobby-db-dao/src/test/resources/datasets/moderators/select.yml
  lobby-db-dao/src/test/resources/datasets/temp_password/sample.yml
  lobby-db-dao/src/test/resources/datasets/temp_password_history/sample.yml
  lobby-db-dao/src/test/resources/datasets/user_lookup/select.yml
  lobby-db/src/main/resources/db/migration/V1.10.00.20190812__temp_password.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190815__temp_password_audit.sql
  lobby/.eclipse/LobbyRunner.launch
  lobby/build.gradle
  lobby/src/main/java/org/triplea/lobby/server/EnvironmentVariable.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/UserManager.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/create/ForgotPasswordModule.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/create/ForgotPasswordModuleFactory.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/create/PasswordEmailSender.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/create/PasswordGenerator.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/create/TempPasswordPersistence.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/verify/TempPasswordVerification.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/forgot/password/create/ForgotPasswordModuleIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/forgot/password/create/ForgotPasswordModuleTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/forgot/password/create/PasswordGeneratorTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/forgot/password/create/TempPasswordPersistenceTest.java
  lobby/src/test/resources/datasets/forgot_password/user_data.yml
Labels: PR: Feature Add

#4997 Refactor: run refresh code on EDT
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/ActionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/BattlePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PurchasePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/RepairPanel.java
Labels: PR: Refactor

#5001 Remove workaround for java5 swing bug
  swing-lib/src/main/java/org/triplea/swing/AutoCompletion.java
Labels: PR: Feature Removal

#5004 Refactor: use lombok
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLoginPreferences.java
Labels: PR: Refactor

#5005 Refactor: use lombok
  game-core/src/main/java/games/strategy/engine/vault/VaultId.java
Labels: PR: Refactor

#5006 Refactor: use lombok
  game-core/src/main/java/games/strategy/net/GUID.java
Labels: PR: Refactor

#5008 Refactor: use lombok
  game-core/src/main/java/games/strategy/triplea/delegate/Die.java
Labels: PR: Refactor

#5000 Remove Mac Java 8 Handler code
  game-core/src/main/java/games/strategy/triplea/ui/MacOsIntegration.java
  game-core/src/test/java/games/strategy/triplea/ui/MacOsIntegrationTest.java
Labels: PR: Feature Removal

#5014 Fix: Handle save game file not found
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/game/selector/GameSelectorPanel.java
Labels: PR: Problem Fix

#5032 Remove unused nested class as identified by ErrorProne
  http-clients/src/test/java/org/triplea/http/client/HttpClientTesting.java
Labels: PR: Refactor

#5038 Fix UnsupportedOperationException when selecting previous units
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Problem Fix

#5039 Unit scroller improvements
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSettingSwingUiBinding.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Feature Update

#5056 Allow air units to move when unloading
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
Labels: PR: Feature Update

#5064 Fix double casualties being shown
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/HeadedLaunchAction.java
Labels: PR: Problem Fix

#5043 Properly catch unwrapped exception
  game-core/src/main/java/games/strategy/engine/framework/ServerGame.java
Labels: PR: Problem Fix

#5062 Replace key listeners with key bindings
  game-core/src/main/java/games/strategy/triplea/ui/KeyBindingSupplier.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
  game-core/src/test/java/games/strategy/triplea/ui/KeyBindingsTest.java
Labels: PR: Problem Fix

#5065 Suppress Travis pack200 errors
  .travis.yml
Labels: PR: Problem Fix

#5066 Blank email is not allowed in client or server.
  game-core/src/main/java/games/strategy/engine/lobby/client/login/CreateUpdateAccountPanel.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
Labels: PR: Problem Fix

#5077 Fix highlight units, correct turn
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
Labels: PR: Problem Fix

#5078 Require playernames to start with a character
  game-core/src/main/java/games/strategy/engine/lobby/PlayerNameValidation.java
  game-core/src/test/java/games/strategy/engine/lobby/PlayerNameValidationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
Labels: PR: Feature Update

#5079 Disallow login with name that is already logged in
  game-core/src/main/java/games/strategy/engine/lobby/PlayerNameValidation.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/test/java/games/strategy/engine/lobby/PlayerNameValidationTest.java
Labels: PR: Feature Update

#5076 Add buttons for highlight units and flags, change flag toggle mode
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/FlagDrawMode.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PlacePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/HelpMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/screen/UnitsDrawer.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerIcon.java
  game-headed/build.gradle
Labels: PR: Feature Add, PR: Feature Update

#5082 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code_design_discussion.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/project_discussion.md
Labels: PR: Configuration Update

#5080 Simplify Version and set to 2.0.0
  .travis.yml
  .travis/setup_gradle
  game-core/build.gradle
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceErrorReportFormatter.java
  game-core/src/main/java/games/strategy/engine/GameEngineVersion.java
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionProperties.java
  game-core/src/main/java/games/strategy/engine/data/GameParser.java
  game-core/src/main/java/games/strategy/engine/framework/GameDataManager.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadFileParser.java
  game-core/src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/game/selector/GameSelectorPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/HelpMenu.java
  game-core/src/main/java/org/triplea/util/Version.java
  game-core/src/main/resources/META-INF/triplea/product.properties
  game-core/src/test/java/games/strategy/debug/error/reporting/StackTraceErrorReportFormatterTest.java
  game-core/src/test/java/games/strategy/engine/GameEngineVersionTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/DownloadFileDescriptionTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/FileDownloadTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/FileSystemStrategyTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/MapDownloadControllerTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/MapDownloadListTest.java
  game-core/src/test/java/games/strategy/engine/framework/startup/mc/GameSelectorModelTest.java
  game-core/src/test/java/org/triplea/config/product/ProductConfigurationIntegrationTest.java
  game-core/src/test/java/org/triplea/config/product/ProductConfigurationTest.java
  game-core/src/test/java/org/triplea/util/VersionTest.java
  game-headed/src/main/java/org/triplea/game/client/ui/javafx/screens/MainMenuPane.java
  game-headed/src/test/java/org/triplea/game/client/ui/javafx/screens/MainMenuPaneTest.java
  gradle/scripts/version.gradle
  infrastructure/run_ansible
Labels: PR: Configuration Update, PR: Refactor

#5085 Update unit scroller, highlight current territory
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSettingSwingUiBinding.java
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Feature Update

#5086 Use invokeLater instead of invokeAndWait
  game-core/src/main/java/games/strategy/triplea/ui/BattlePanel.java
Labels: PR: Problem Fix

#5089 Name de-dupe by MAC instead of by IP
  game-core/src/main/java/games/strategy/net/PlayerNameAssigner.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/test/java/games/strategy/net/PlayerNameAssignerTest.java
Labels: PR: Feature Update

#5084 Add hotkey (shift+d) for 'Done' Button
  game-core/src/main/java/games/strategy/engine/pbem/ForumPosterComponent.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/ActionButtons.java
  game-core/src/main/java/games/strategy/triplea/ui/ActionPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/BattlePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/EditPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/EndTurnPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/MoveForumPosterPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PickTerritoryAndUnitsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PoliticsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PurchasePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/RepairPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TechPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java
Labels: PR: Feature Add

#5097 Fix jar creation ordering
  .travis.yml
Labels: PR: Problem Fix

#5103 DBUnit Clean database before applying dataset
  http-server/src/test/java/org/triplea/server/http/AbstractDropwizardTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/AccessLogDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/BadWordsDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/BannedUserNamesDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ErrorReportingDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ModeratorApiKeyDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ModeratorAuditHistoryDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ModeratorSingleUseKeyDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ModeratorsDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordHistoryDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/UserLookupDaoTest.java
  lobby-db-dao/src/test/resources/datasets/moderator_api_key/select.yml
  lobby-db-dao/src/test/resources/datasets/moderator_api_key/select_post_delete.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/history-select.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/post-insert.yml
  lobby-db-dao/src/test/resources/datasets/moderator_audit/pre-insert.yml
  lobby-db-dao/src/test/resources/datasets/moderator_single_use_key/empty.yml
  lobby-db-dao/src/test/resources/datasets/moderator_single_use_key/select.yml
  lobby-db-dao/src/test/resources/datasets/moderators/select.yml
  lobby-db-dao/src/test/resources/datasets/temp_password/sample.yml
  lobby-db-dao/src/test/resources/datasets/user_lookup/select.yml
  lobby/src/test/java/org/triplea/lobby/server/db/BadWordControllerIntegrationTest.java
Labels: PR: Problem Fix

#5110 Small refactor in DebugMenu, use simpler API of SwingAction
  game-core/src/main/java/games/strategy/triplea/ui/menubar/DebugMenu.java
Labels: PR: Refactor

#5111 SwingBuilders for JMenu, GridBagConstraints, and Refactor Game Menus
  game-core/src/main/java/games/strategy/engine/framework/ui/PropertiesSelector.java
  game-core/src/main/java/games/strategy/sound/SoundOptions.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ExportMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/FileMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/GameMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  java-extras/src/main/java/org/triplea/java/ArgChecker.java
  java-extras/src/test/java/org/triplea/java/ArgCheckerTest.java
  swing-lib/src/main/java/org/triplea/swing/GridBagConstraintsAnchor.java
  swing-lib/src/main/java/org/triplea/swing/GridBagConstraintsBuilder.java
  swing-lib/src/main/java/org/triplea/swing/GridBagConstraintsFill.java
  swing-lib/src/main/java/org/triplea/swing/JMenuBuilder.java
  swing-lib/src/main/java/org/triplea/swing/JMenuItemBuilder.java
  swing-lib/src/main/java/org/triplea/swing/JMenuItemCheckBoxBuilder.java
  swing-lib/src/main/java/org/triplea/swing/JPanelBuilder.java
  swing-lib/src/main/java/org/triplea/swing/KeyCode.java
  swing-lib/src/test/java/org/triplea/swing/JMenuBuilderTest.java
  swing-lib/src/test/java/org/triplea/swing/JMenuItemBuilderTest.java
  swing-lib/src/test/java/org/triplea/swing/JMenuItemCheckBoxBuilderTest.java
Labels: PR: Feature Update, PR: Refactor

#5122 Fix pre-release to release bad enum value problem for flag settings
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
Labels: PR: Problem Fix

#5128 Forgot password messenger cleanup
  game-core/src/main/java/games/strategy/net/ClientMessengerFactory.java
Labels: PR: Refactor

#5129 Introduce UserJdbiDao Refactor
  http-server/src/main/java/org/triplea/server/moderator/toolbox/api/key/ApiKeyControllerFactory.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/api/key/GenerateSingleUseKeyService.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsControllerFactory.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsService.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/api/key/GenerateSingleUseKeyServiceTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsServiceTest.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/UserJdbiDao.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/UserLookupDao.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/UserJdbiDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/UserLookupDaoTest.java
  lobby-db-dao/src/test/resources/datasets/user/select.yml
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedMacController.java
  lobby/src/main/java/org/triplea/lobby/server/db/DatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/JdbcDatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/UserController.java
  lobby/src/main/java/org/triplea/lobby/server/db/UserDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/UsernameBlacklistController.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/test/java/org/triplea/lobby/server/db/UserControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
Labels: PR: Refactor

#5118 Use jakarta dependency
  README.md
  build.gradle
  game-core/build.gradle
  http-server/build.gradle
Labels: PR: Testing

#5149 Update version compatibility algorithm
  game-core/src/main/java/org/triplea/util/Version.java
  game-core/src/test/java/org/triplea/util/VersionTest.java
Labels: PR: Feature Update

#5151 Update verify script, combine commands to one
  verify
Labels: PR: Configuration Update

#5148 JMenuItem Checkbox Persistence
  game-core/src/main/java/games/strategy/sound/ClipPlayer.java
  game-core/src/main/java/games/strategy/sound/SoundOptionCheckBox.java
  game-core/src/main/java/games/strategy/sound/SoundOptions.java
  game-core/src/main/java/games/strategy/triplea/settings/BooleanClientSetting.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractUiContext.java
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/PurchasePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/UiContext.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  swing-lib/src/main/java/org/triplea/swing/JMenuItemCheckBoxBuilder.java
Labels: PR: Feature Update

#5146 Faster Builds with Parallel travis VMs
  .travis.yml
  .travis/install
Labels: PR: Configuration Update

#5152 Simplify flag view menu options and refactor code
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/ui/FlagDrawMode.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/screen/UnitsDrawer.java
Labels: PR: Feature Update, PR: Refactor
