Repository triplea-game/triplea, pull requests merged in 2019-12, with the labels that each got.

#5622 Replace HashedMac with SystemId
  domain-data/src/main/java/org/triplea/domain/data/SystemIdLoader.java
  domain-data/src/test/java/org/triplea/domain/data/SystemIdLoaderTest.java
  game-core/src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/ClientMessengerFactory.java
  game-core/src/main/java/games/strategy/net/MacFinder.java
  game-core/src/main/java/games/strategy/net/nio/ClientQuarantineConversation.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/framework/startup/login/ClientLoginIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/message/unifiedmessenger/ChannelMessengerTest.java
  game-core/src/test/java/games/strategy/engine/message/unifiedmessenger/RemoteMessengerTest.java
  game-core/src/test/java/games/strategy/engine/vault/VaultTest.java
  game-core/src/test/java/games/strategy/net/MacFinderTest.java
  game-core/src/test/java/games/strategy/net/MessengerIntegrationTest.java
  http-clients/src/main/java/org/triplea/http/client/SystemIdHeader.java
  http-clients/src/test/java/org/triplea/http/client/SystemIdHeaderTest.java
Labels: PR: Cleanup/Simplification

#5621 Add Client components for RemoteAction polling
  game-core/src/main/java/games/strategy/net/INode.java
  game-core/src/main/java/org/triplea/game/server/ban/check/PlayerDisconnectAction.java
  game-core/src/main/java/org/triplea/game/server/ban/check/RemoteActionsPoller.java
  game-core/src/test/java/games/strategy/net/INodeTest.java
  game-core/src/test/java/org/triplea/game/server/ban/check/PlayerDisconnectActionTest.java
  game-core/src/test/java/org/triplea/game/server/ban/check/RemoteActionsPollerTest.java
  http-clients/src/main/java/org/triplea/http/client/IpAddressParser.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/hosting/GameHostingResponse.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/remote/actions/BannedPlayer.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/remote/actions/RemoteActions.java
  http-clients/src/main/java/org/triplea/http/client/lobby/game/remote/actions/RemoteActionsClient.java
  http-clients/src/test/java/org/triplea/http/client/IpAddressParserTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/game/remote/actions/RemoteActionsTest.java
Labels: PR: More to Follow

#5616 Move LobbyWatcherThread ownership to ServerModel, prep for ServerPoller
  game-core/src/main/java/games/strategy/engine/framework/network/ui/SetPasswordAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/LobbyWatcherThread.java
  game-core/src/main/java/games/strategy/engine/framework/startup/WatcherThreadMessaging.java
  game-core/src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/SetupPanelModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/RemoteHostUtils.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/net/ILoginValidator.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/game/server/HeadlessLaunchAction.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetupPanelModel.java
  game-core/src/main/java/org/triplea/game/startup/ServerSetupModel.java
  game-core/src/main/java/org/triplea/game/startup/SetupModel.java
  game-core/src/main/java/org/triplea/lobby/common/IModeratorController.java
  game-core/src/main/java/org/triplea/lobby/common/IRemoteHostUtils.java
  game-core/src/test/java/games/strategy/engine/framework/startup/login/ClientLoginIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/framework/startup/login/ClientLoginValidatorTest.java
Labels: PR: More to Follow

#5619 Show warning when attacking a territory that can be defended by scramblers.
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProScrambleAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/ScrambleLogic.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
Labels: PR: Feature Add

#5578 Optimization: Remove unnecessary collection copies.
  game-core/src/main/java/games/strategy/triplea/TripleAUnit.java
  game-core/src/main/java/games/strategy/triplea/ai/fast/AggregateEstimate.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProNonCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProScrambleAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/simulate/ProSimulateTurnUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProOddsCalculator.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleResults.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleTracker.java
  game-core/src/main/java/games/strategy/triplea/delegate/FinishedBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/IBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/Matches.java
  game-core/src/main/java/games/strategy/triplea/delegate/MustFightBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/NonFightingBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/TransportTracker.java
  game-core/src/main/java/games/strategy/triplea/odds/calculator/AggregateResults.java
Labels: PR: Cleanup/Simplification

#5650 Handle zero ban minutes
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/BanDurationFormatter.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/BanDurationFormatterTest.java
Labels: PR: Problem Fix

#5651 Fix Node null address when using unresolved IP addresses
  game-core/src/main/java/games/strategy/net/Node.java
  game-core/src/test/java/games/strategy/net/NodeTest.java
Labels: PR: Problem Fix

#5652 Remove unused error message
  game-core/src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java
Labels: PR: Cleanup/Simplification

#5661 Enable and test http-endpoint Roles
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameListingController.java
  http-server/src/test/java/org/triplea/http/server/LobbyChatIntegrationTest.java
  http-server/src/test/java/org/triplea/server/http/AllowedUserRole.java
  http-server/src/test/java/org/triplea/server/http/BasicEndpointTest.java
  http-server/src/test/java/org/triplea/server/http/ProtectedEndpointTest.java
  http-server/src/test/java/org/triplea/server/lobby/chat/moderation/ModeratorLobbyControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/ConnectivityControllerTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/listing/GameListingControllerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/access/log/AccessLogControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/audit/history/ModeratorAuditHistoryControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/bad/words/BadWordsControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/banned/names/UsernameBanControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/banned/users/UserBanControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/remote/actions/RemoteActionsControllerIntegrationTest.java
  http-server/src/test/java/org/triplea/server/user/account/UserAccountControllerIntegrationTest.java
  http-server/src/test/resources/datasets/integration.yml
Labels: PR: Problem Fix

#5555 Update NGINX SSL settings
  infrastructure/README-VAGRANT-DEV.md
  infrastructure/ansible/roles/nginx/defaults/main.yml
  infrastructure/ansible/roles/nginx/tasks/main.yml
  infrastructure/ansible/roles/nginx/templates/etc_nginx_sites_enabled_default.j2
Labels: PR: Configuration Update

#5722 Enable HTTP/2 and IPv6 for spitfire nginx config
  infrastructure/ansible/roles/nginx/tasks/main.yml
  infrastructure/ansible/roles/nginx/templates/etc_nginx_sites_enabled_default.j2
Labels: PR: Configuration Update, PR: Dev Infrastructure

#5737 Replace static constructor method with static import
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/messages/server/ChatServerMessageType.java
  http-clients/src/main/java/org/triplea/http/client/remote/actions/messages/server/ServerRemoteActionMessageType.java
  http-clients/src/main/java/org/triplea/http/client/web/socket/messages/MessageTypeListenerBinding.java
  http-clients/src/test/java/org/triplea/http/client/web/socket/messages/WebsocketMessageTypeTest.java
Labels: PR: More to Follow

#5738 Add utility to create websocket listeners
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  http-clients/src/main/java/org/triplea/http/client/remote/actions/RemoteActionListeners.java
  http-clients/src/main/java/org/triplea/http/client/remote/actions/RemoteActionsWebsocketListener.java
  http-clients/src/main/java/org/triplea/http/client/web/socket/WebsocketListenerFactory.java
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
  http-server/src/main/java/org/triplea/server/remote/actions/RemoteActionsWebSocket.java
Labels: PR: More to Follow

#5759 Remove redundant (bot-game) user action list
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/LocalSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/MetaSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/PbemSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/SetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
Labels: PR: Feature Removal
