Repository triplea-game/triplea, pull requests merged in 2019-10, with the labels that each got.

#5310 Add a toString to ChatParticipant for Debug
  game-core/src/main/java/games/strategy/engine/chat/ChatParticipant.java
Labels: PR: Refactor

#5312 Send bot messages line by line, restore message cap to hosts
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-headless/src/main/java/org/triplea/game/server/debug/ChatHandler.java
  game-headless/src/test/java/org/triplea/game/server/debug/ChatHandlerTest.java
Labels: PR: Feature Update, PR: More to Follow, PR: Problem Fix, PR: Refactor

#5313 Chat Refactors: IChatListener breakup, chat history fix, constructor injection
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessageListener.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPlayerListener.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPlayerPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
Labels: PR: More to Follow, PR: Problem Fix, PR: Refactor

#5321 Remove duplicate dependency in http-clients build.gradle file
  game-core/build.gradle
  http-clients/build.gradle
  http-server/build.gradle
Labels: PR: More to Follow, PR: Refactor

#5323 build.gradle consistency updates: dependencies
  build.gradle
  game-core/build.gradle
  game-headed/build.gradle
  http-server/build.gradle
  lobby-db-dao/build.gradle
  lobby/build.gradle
Labels: PR: More to Follow, PR: Refactor

#5327 Refactor: Postconditions rename and better failure message
  java-extras/src/main/java/org/triplea/java/Postconditions.java
  java-extras/src/test/java/org/triplea/java/PostconditionsTest.java
  swing-lib/src/main/java/org/triplea/swing/jpanel/SimpleGridBagLayoutBuilder.java
Labels: PR: More to Follow, PR: Refactor

#5328 Add utility 'CacheUtils' for working with expireAfterWriteCaches
  http-server/src/main/java/org/triplea/server/lobby/CacheUtils.java
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameListing.java
  http-server/src/test/java/org/triplea/server/lobby/CacheUtilsTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/listing/GameListingTest.java
Labels: PR: More to Follow, PR: Refactor

#5330 Introduce 'DaoTest' utility base class
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/AccessLogDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/BadWordsDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/BannedUserNamesDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/DaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ErrorReportingDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ModeratorAuditHistoryDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/ModeratorsDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordHistoryDaoTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/UserJdbiDaoTest.java
Labels: PR: More to Follow, PR: Refactor

#5329 Refactor: Chat API objects
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatClient.java
  game-core/src/main/java/games/strategy/engine/chat/ChatController.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessage.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessageListener.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPlayerListener.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPlayerPanel.java
  game-core/src/main/java/games/strategy/engine/chat/ChatTransmitter.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/chat/IChatChannel.java
  game-core/src/main/java/games/strategy/engine/chat/IChatController.java
  game-core/src/main/java/games/strategy/engine/chat/IPlayerActionFactory.java
  game-core/src/main/java/games/strategy/engine/chat/MessengersChatTransmitter.java
  game-core/src/main/java/games/strategy/engine/chat/PlayerChatRenderer.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/ChatParticipant.java
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/events/server/ChatMessage.java
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/events/server/StatusUpdate.java
Labels: PR: More to Follow, PR: Refactor

#5334 Add Chat 'Connected' API and use 'set' for chatters
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatClient.java
Labels: PR: More to Follow

#5335 Update ServerModel to return 'PlayerName' instead of String
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerOptions.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
Labels: PR: More to Follow, PR: Refactor

#5336 Consolidate TestData to utility classes
  game-core/src/test/java/games/strategy/engine/lobby/client/ui/GamePollerTaskTest.java
  game-core/src/test/java/org/triplea/lobby/common/GameDescriptionTest.java
  game-core/src/test/java/org/triplea/test/TestData.java
  http-clients/src/test/java/org/triplea/http/client/TestData.java
  http-clients/src/test/java/org/triplea/http/client/lobby/game/listing/GameListingClientTest.java
  http-server/src/test/java/org/triplea/server/TestData.java
  http-server/src/test/java/org/triplea/server/access/ApiKeyAuthenticatorTest.java
  http-server/src/test/java/org/triplea/server/lobby/game/listing/GameListingControllerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/bad/words/BadWordsControllerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/banned/names/UsernameBanControllerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/banned/users/UserBanControllerTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/moderators/ModeratorsControllerTest.java
Labels: PR: More to Follow, PR: Refactor

#5338 Refactor: inline ip extractor
  http-server/src/main/java/org/triplea/server/error/reporting/ErrorReportController.java
  http-server/src/main/java/org/triplea/server/http/IpAddressExtractor.java
  http-server/src/test/java/org/triplea/server/http/IpAddressExtractorTest.java
Labels: PR: Refactor

#5337 Wire IP address to api-key-generator
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  http-server/src/main/java/org/triplea/server/access/ApiKeyGenerator.java
  http-server/src/main/java/org/triplea/server/lobby/game/hosting/GameHostingController.java
  lobby/src/main/java/org/triplea/lobby/server/api/key/ApiKeyGeneratorFactory.java
Labels: PR: More to Follow, PR: Refactor

#5342 Make "Flag Display Mode" menu items mutually exclusive with radio buttons.
  game-core/src/main/java/games/strategy/triplea/ui/menubar/ViewMenu.java
  swing-lib/src/main/java/org/triplea/swing/JMenuItemBuilder.java
Labels: PR: Work In Progress

#5368 Validate Account Creation on Key-Type
  game-core/src/main/java/games/strategy/engine/lobby/client/login/CreateAccountPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/moderators/ModeratorsTab.java
  swing-lib/src/main/java/org/triplea/swing/KeyTypeValidator.java
Labels: PR: Feature Update

#5371 Http-server login components
  domain-data/src/main/java/org/triplea/domain/data/PlayerChatId.java
  http-server/build.gradle
  http-server/src/main/java/org/triplea/server/user/account/PasswordBCrypter.java
  http-server/src/main/java/org/triplea/server/user/account/login/AccessLogUpdater.java
  http-server/src/main/java/org/triplea/server/user/account/login/ApiKeyGenerator.java
  http-server/src/main/java/org/triplea/server/user/account/login/LoginController.java
  http-server/src/main/java/org/triplea/server/user/account/login/LoginControllerFactory.java
  http-server/src/main/java/org/triplea/server/user/account/login/LoginModule.java
  http-server/src/main/java/org/triplea/server/user/account/login/LoginRecord.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/BCryptHashVerifier.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/anonymous/AnonymousLogin.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/anonymous/AnonymousLoginFactory.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/legacy/LegacyPasswordCheck.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/legacy/LegacyPasswordUpdate.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/legacy/Md5Crypt.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/registered/PasswordCheck.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/registered/RegisteredLogin.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/registered/RegisteredLoginFactory.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/temp/password/TempPasswordLogin.java
  http-server/src/test/java/org/triplea/server/user/account/PasswordBcrypterTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/LoginControllerTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/LoginModuleTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/BCryptHashVerifierTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/anonymous/AnonymousLoginTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/legacy/LegacyPasswordCheckTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/legacy/LegacyPasswordUpdateTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/registered/PasswordCheckTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/registered/RegisteredLoginTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/temp/password/TempPasswordLoginTest.java
  integration-testing/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordDaoTest.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/TempPasswordDao.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/UserJdbiDao.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/data/UserRole.java
  lobby/src/main/java/org/triplea/lobby/server/login/forgot/password/verify/TempPasswordVerification.java
Labels: PR: More to Follow
