Repository triplea-game/triplea, pull requests merged in 2019-03, with the labels that each got.

#4726 Move a few utilities to java-extras
  java-extras/src/main/java/games/strategy/engine/framework/system/SystemProperties.java
  java-extras/src/main/java/games/strategy/io/FileUtils.java
  java-extras/src/main/java/games/strategy/io/IoUtils.java
  java-extras/src/main/java/games/strategy/triplea/util/WrappedInvocationHandler.java
Labels: PR: Refactor

#4727 ClientQuarantine Simplify
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ClientQuarantineConversation.java
  game-core/src/main/java/games/strategy/net/nio/QuarantineConversation.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
Labels: PR: Refactor

#4725 NIO Cleanup Refactoring
  game-core/src/main/java/games/strategy/net/AbstractServerMessenger.java
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/HeadlessServerMessenger.java
  game-core/src/main/java/games/strategy/net/IMessenger.java
  game-core/src/main/java/games/strategy/net/MessageHeader.java
  game-core/src/main/java/games/strategy/net/nio/Decoder.java
  game-core/src/main/java/games/strategy/net/nio/Encoder.java
  game-core/src/main/java/games/strategy/net/nio/NioReader.java
  game-core/src/main/java/games/strategy/net/nio/NioSocket.java
  game-core/src/main/java/games/strategy/net/nio/NioWriter.java
  game-core/src/main/java/games/strategy/net/nio/SocketReadData.java
  game-core/src/test/java/games/strategy/net/MessengerIntegrationTest.java
Labels: PR: Refactor

#4728 Simplify No-Op DelegateHistoryWriter
  game-core/src/main/java/games/strategy/engine/history/DelegateHistoryWriter.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/simulate/ProDummyDelegateBridge.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/simulate/ProDummyGameModifiedChannel.java
  game-core/src/test/java/games/strategy/triplea/delegate/MockDelegateBridge.java
Labels: PR: Refactor

#4723 Refactoring: Consolidate Messengers API
  game-core/src/main/java/games/strategy/engine/chat/Chat.java
  game-core/src/main/java/games/strategy/engine/chat/ChatController.java
  game-core/src/main/java/games/strategy/engine/chat/ChatPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/chat/StatusController.java
  game-core/src/main/java/games/strategy/engine/chat/StatusManager.java
  game-core/src/main/java/games/strategy/engine/delegate/DefaultDelegateBridge.java
  game-core/src/main/java/games/strategy/engine/framework/AbstractGame.java
  game-core/src/main/java/games/strategy/engine/framework/ClientGame.java
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/framework/HistorySynchronizer.java
  game-core/src/main/java/games/strategy/engine/framework/IGame.java
  game-core/src/main/java/games/strategy/engine/framework/ServerGame.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/ServerLauncher.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/LobbyClient.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
  game-core/src/main/java/games/strategy/engine/pbem/ForumPosterComponent.java
  game-core/src/main/java/games/strategy/engine/player/DefaultPlayerBridge.java
  game-core/src/main/java/games/strategy/engine/random/CryptoRandomSource.java
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/IMessenger.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/Messengers.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/GameMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/NetworkMenu.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/TripleAMenuBar.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModelTest.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
Labels: PR: Refactor

#4729 Rename HeadlessServerMessenger.java -> LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/engine/framework/startup/launcher/LocalLauncher.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
Labels: PR: Refactor

#4730 Vacate one of the Util.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/DiceServerEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/EmailSenderEditor.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/editors/ForumPosterEditor.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/CreateUpdateAccountPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/server/userDB/DBUser.java
  game-core/src/test/java/games/strategy/engine/framework/startup/ui/editors/ForumPosterEditorTest.java
  java-extras/src/main/java/org/triplea/java/StringUtils.java
  java-extras/src/main/java/org/triplea/java/Util.java
  java-extras/src/test/java/org/triplea/java/StringUtilsTest.java
  java-extras/src/test/java/org/triplea/java/UtilTest.java
  lobby/src/test/java/org/triplea/lobby/server/ModeratorControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/TestUserUtils.java
  lobby/src/test/java/org/triplea/lobby/server/db/AccessLogControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/BadWordControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/BannedMacControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/EmailLimitIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/HashedPasswordTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/MutedMacControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/UserControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
Labels: PR: Refactor

#4734 Cleanup, DB Layer: Consistent DAO interfaces and configuration
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServerMessenger.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/UserManager.java
  lobby/src/main/java/org/triplea/lobby/server/config/LobbyConfiguration.java
  lobby/src/main/java/org/triplea/lobby/server/db/AbstractController.java
  lobby/src/main/java/org/triplea/lobby/server/db/AccessLogController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BadWordController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedMacController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedMacDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedUsernameController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedUsernameDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/Database.java
  lobby/src/main/java/org/triplea/lobby/server/db/DatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/DatabaseException.java
  lobby/src/main/java/org/triplea/lobby/server/db/JdbcDatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedMacController.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedMacDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedUsernameController.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedUsernameDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/TimedController.java
  lobby/src/main/java/org/triplea/lobby/server/db/UserController.java
  lobby/src/main/java/org/triplea/lobby/server/db/UserDao.java
  lobby/src/main/java/org/triplea/lobby/server/login/AccessLog.java
  lobby/src/main/java/org/triplea/lobby/server/login/CompositeAccessLog.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/test/java/org/triplea/lobby/server/ModeratorControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/AbstractControllerTestCase.java
  lobby/src/test/java/org/triplea/lobby/server/db/AbstractModeratorServiceControllerTestCase.java
  lobby/src/test/java/org/triplea/lobby/server/db/AccessLogControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/BadWordControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/BannedMacControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/BannedUsernameControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/EmailLimitIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/MutedMacControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/MutedUsernameControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/TestDatabase.java
  lobby/src/test/java/org/triplea/lobby/server/db/UserControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/CompositeAccessLogTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
Labels: PR: Refactor

#4732 Simplify Network Serialization of MessageHeader
  game-core/src/main/java/games/strategy/net/MessageHeader.java
  game-core/src/main/java/games/strategy/net/nio/Decoder.java
  game-core/src/main/java/games/strategy/net/nio/Encoder.java
  game-core/src/main/java/games/strategy/net/nio/NioSocket.java
Labels: PR: Refactor

#4745 Add DB Rider & Update BadWordDao 'list' API to be a 'contains'
  lobby/build.gradle
  lobby/src/main/java/org/triplea/lobby/server/db/BadWordController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BadWordDao.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/test/java/org/triplea/lobby/server/db/BadWordControllerIntegrationTest.java
  lobby/src/test/resources/datasets/badwords/bad.yml
  lobby/src/test/resources/datasets/badwords/post-insert.yml
  lobby/src/test/resources/datasets/badwords/pre-insert.yml
  lobby/src/test/resources/dbunit.yml
Labels: PR: Refactor

#4744 Use Lombok annotations with Node.java
  game-core/src/main/java/games/strategy/net/Node.java
Labels: PR: Refactor

#4737 Try to fix concurrency issue 1.10
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
Labels: PR: Testing

#4743 Update Feature: No time duration when banning on remote
  game-core/src/main/java/games/strategy/engine/framework/network/ui/BanPlayerAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/RemoteHostUtils.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/net/AbstractServerMessenger.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/lobby/common/IModeratorController.java
  game-core/src/main/java/org/triplea/lobby/common/IRemoteHostUtils.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
Labels: PR: Feature Update, PR: Refactor

#4758 Add lobby version number to DB migration files and squash
  docs/dev/making_database_changes.md
  lobby-db/src/main/resources/db/migration/V1.00.00__lobby.sql
  lobby-db/src/main/resources/db/migration/V1.01__update_tables.sql
  lobby-db/src/main/resources/db/migration/V1.02__add_bcrypt_password_column.sql
  lobby-db/src/main/resources/db/migration/V1.03__audit_bans.sql
  lobby-db/src/main/resources/db/migration/V1.04__audit_mutes.sql
  lobby-db/src/main/resources/db/migration/V1.05__add_all_user_info_to_bans_and_mutes.sql
  lobby-db/src/main/resources/db/migration/V1.06__add_access_log.sql
  lobby-db/src/main/resources/db/migration/V1.09.00__lobby.sql
  lobby-db/src/main/resources/db/migration/V1.10.00__lobby.sql
Labels: PR: Refactor

#4762 Simplify mini-ban and mini-muting, name bans become permament
  game-core/src/main/java/games/strategy/engine/framework/network/ui/BanPlayerAction.java
  game-core/src/main/java/games/strategy/engine/framework/network/ui/MutePlayerAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/net/AbstractServerMessenger.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/lobby/common/IModeratorController.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  lobby-db/src/main/resources/db/migration/V1.10.00.20190313.1200__delete_mute_by_username.sql
  lobby/src/main/java/org/triplea/lobby/server/LobbyServerMessenger.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedUsernameController.java
  lobby/src/main/java/org/triplea/lobby/server/db/BannedUsernameDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/DatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/JdbcDatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedUsernameController.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedUsernameDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/UsernameBlacklistController.java
  lobby/src/main/java/org/triplea/lobby/server/db/UsernameBlacklistDao.java
  lobby/src/main/java/org/triplea/lobby/server/login/LobbyLoginValidator.java
  lobby/src/test/java/org/triplea/lobby/server/db/BannedUsernameControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/db/MutedUsernameControllerIntegrationTest.java
  lobby/src/test/java/org/triplea/lobby/server/login/LobbyLoginValidatorTest.java
Labels: PR: Feature Removal, PR: Refactor

#4763 Muted_macs remove columns
  lobby-db/src/main/resources/db/migration/V1.10.00.201903131400__drop_muted_mac_columns.sql
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedMacController.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedMacDao.java
  lobby/src/test/java/org/triplea/lobby/server/db/MutedMacControllerIntegrationTest.java
Labels: PR: Refactor

#4779 Object rename: 'ErrorReport*' to ErrorUpload*
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ConfirmationDialogController.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportUploadAction.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ReportPreviewSwingView.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceErrorReportFormatter.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportModel.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportView.java
  game-core/src/test/java/games/strategy/debug/error/reporting/ErrorReportUploadActionTest.java
  game-core/src/test/java/games/strategy/debug/error/reporting/StackTraceErrorReportFormatterTest.java
  game-core/src/test/java/games/strategy/debug/error/reporting/StackTraceReportModelTest.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadClientFactory.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadRequest.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadResponse.java
  lobby-client-http/src/main/java/org/triplea/http/client/github/issues/GithubIssueClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/github/issues/GithubIssueClientFactory.java
  lobby-client-http/src/test/java/org/triplea/http/client/error/report/ErrorReportClientTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/error/report/ErrorReportResponseTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/throttle/rate/RateLimitingThrottleTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/throttle/size/MessageSizeThrottleTest.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorReportRequest.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorReportResponseAdapter.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorUploadConfiguration.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorUploadStrategy.java
  lobby-engine/src/test/java/org/triplea/server/reporting/error/ErrorReportResponseAdapterTest.java
  lobby-engine/src/test/java/org/triplea/server/reporting/error/ErrorUploadStrategyTest.java
  lobby/src/main/java/org/triplea/server/http/spark/controller/ErrorReportController.java
  lobby/src/test/java/org/triplea/server/http/spark/SparkServerSystemTest.java
Labels: PR: Refactor

#4780 Remove client-side http throttling
  lobby-client-http/src/main/java/org/triplea/http/client/HttpClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/RateLimiter.java
  lobby-client-http/src/main/java/org/triplea/http/client/throttle/MessageNotSentException.java
  lobby-client-http/src/main/java/org/triplea/http/client/throttle/rate/RateLimitException.java
  lobby-client-http/src/main/java/org/triplea/http/client/throttle/rate/RateLimitingThrottle.java
  lobby-client-http/src/main/java/org/triplea/http/client/throttle/size/MessageExceedsMaxSizeException.java
  lobby-client-http/src/main/java/org/triplea/http/client/throttle/size/MessageSizeThrottle.java
  lobby-client-http/src/test/java/org/triplea/http/client/throttle/rate/RateLimitingThrottleTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/throttle/size/MessageSizeThrottleTest.java
Labels: PR: Feature Removal, PR: Refactor

#4783 Drop mutes & Simplify
  game-core/src/main/java/games/strategy/engine/chat/AdministrativeChatMessages.java
  game-core/src/main/java/games/strategy/engine/chat/ChatMessagePanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/framework/network/ui/MutePlayerAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/GameServerMessenger.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/ServerModel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/RemoteHostUtils.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  game-core/src/main/java/games/strategy/triplea/ui/menubar/NetworkMenu.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/lobby/common/IModeratorController.java
  game-core/src/main/java/org/triplea/lobby/common/IRemoteHostUtils.java
  game-core/src/test/java/games/strategy/engine/chat/ChatIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/framework/startup/login/ClientLoginIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/message/unifiedmessenger/ChannelMessengerTest.java
  game-core/src/test/java/games/strategy/engine/message/unifiedmessenger/RemoteMessengerTest.java
  game-core/src/test/java/games/strategy/engine/vault/VaultTest.java
  game-core/src/test/java/games/strategy/net/MessengerIntegrationTest.java
  game-core/src/test/java/games/strategy/net/TestServerMessenger.java
  lobby-db/src/main/resources/db/migration/V1.10.00.201903131400__drop_muted_mac_columns.sql
  lobby-db/src/main/resources/db/migration/V1.10.00.20190320__drop_mutes.sql
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServerMessenger.java
  lobby/src/main/java/org/triplea/lobby/server/ModeratorController.java
  lobby/src/main/java/org/triplea/lobby/server/db/DatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/JdbcDatabaseDao.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedMacController.java
  lobby/src/main/java/org/triplea/lobby/server/db/MutedMacDao.java
  lobby/src/test/java/org/triplea/lobby/server/db/MutedMacControllerIntegrationTest.java
Labels: PR: Feature Removal, PR: Refactor

#4785 Merge ansible http-server deployment scripts into lobby
  infrastructure/ansible/roles/http_server/defaults/main.yml
  infrastructure/ansible/roles/http_server/tasks/main.yml
  infrastructure/ansible/roles/http_server/templates/http-server.service.j2
  infrastructure/ansible/roles/http_server/templates/run_server.j2
  infrastructure/ansible/roles/lobby/defaults/main.yml
  infrastructure/ansible/roles/lobby/templates/lobby.service.j2
Labels: Infrastructure

#4784 Simplify ban player API
  game-core/src/main/java/games/strategy/engine/framework/network/ui/BanPlayerAction.java
  game-core/src/main/java/games/strategy/engine/framework/startup/login/ClientLoginValidator.java
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
Labels: PR: Refactor

#4782 Fix chat panel not rendering on game staging screen.
  game-core/src/main/java/games/strategy/engine/chat/ChatPanel.java
  game-core/src/main/java/games/strategy/engine/chat/HeadlessChat.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanelBuilder.java
  game-core/src/main/java/org/triplea/game/chat/ChatModel.java
Labels: PR: Bug Fix

#4787 Documentation: Add README to lobby-client-http sub-project
  lobby-client-http/README.md
Labels: PR: Documentation-Only

#4786 Expose Feign Http Clients / Drop ServiceResponse Wrapper
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ConfirmationDialogController.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportUploadAction.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportView.java
  game-core/src/test/java/games/strategy/debug/error/reporting/ErrorReportUploadActionTest.java
  lobby-client-http/build.gradle
  lobby-client-http/src/main/java/org/triplea/http/client/FeignFactory.java
  lobby-client-http/src/main/java/org/triplea/http/client/HttpClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/HttpCommunicationException.java
  lobby-client-http/src/main/java/org/triplea/http/client/SendResult.java
  lobby-client-http/src/main/java/org/triplea/http/client/ServiceClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/ServiceResponse.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadClientFactory.java
  lobby-client-http/src/main/java/org/triplea/http/client/error/report/ErrorUploadResponse.java
  lobby-client-http/src/main/java/org/triplea/http/client/github/issues/GithubClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/github/issues/GithubIssueClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/github/issues/GithubIssueClientFactory.java
  lobby-client-http/src/main/java/org/triplea/http/client/github/issues/IssueClientParams.java
  lobby-client-http/src/test/java/org/triplea/http/client/HttpClientTesting.java
  lobby-client-http/src/test/java/org/triplea/http/client/ServiceResponseTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/error/report/ErrorReportClientTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/error/report/ErrorReportResponseTest.java
  lobby-client-http/src/test/java/org/triplea/http/client/github/issues/GithubIssueClientTest.java
  lobby-engine/build.gradle
  lobby-engine/src/main/java/org/triplea/server/reporting/error/CreateErrorReportException.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/CreateIssueStrategy.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorReportGateKeeper.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorReportResponseAdapter.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorReportResponseConverter.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorUploadConfiguration.java
  lobby-engine/src/main/java/org/triplea/server/reporting/error/ErrorUploadStrategy.java
  lobby-engine/src/test/java/org/triplea/server/reporting/error/ErrorReportResponseAdapterTest.java
  lobby-engine/src/test/java/org/triplea/server/reporting/error/ErrorUploadStrategyTest.java
  lobby/src/main/java/org/triplea/lobby/server/EnvironmentVariable.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyRunner.java
  lobby/src/main/java/org/triplea/server/EnvironmentVariable.java
  lobby/src/main/java/org/triplea/server/ServerConfiguration.java
  lobby/src/main/java/org/triplea/server/http/spark/SparkServer.java
  lobby/src/main/java/org/triplea/server/http/spark/controller/ErrorReportController.java
  lobby/src/test/java/org/triplea/server/http/spark/ErrorReportControllerTest.java
  lobby/src/test/java/org/triplea/server/http/spark/SparkServerSystemTest.java
Labels: PR: Refactor

#4796 Let ErrorController throw errors
  lobby/src/main/java/org/triplea/server/http/spark/controller/ErrorReportController.java
Labels: PR: Bug Fix

#4797 Move test documentation to a README
  lobby-client-http/src/test/java/org/triplea/http/client/README.md
  lobby-client-http/src/test/java/org/triplea/http/client/error/report/ErrorReportClientTest.java
Labels: PR: Documentation-Only

#4795 Add Http LobbyLogin client with stubbed server controller
  lobby-client-http/src/main/java/org/triplea/http/client/lobby/login/LobbyLoginClient.java
  lobby-client-http/src/main/java/org/triplea/http/client/lobby/login/LobbyLoginResponse.java
  lobby-client-http/src/main/java/org/triplea/http/client/lobby/login/RegisteredUserLoginRequest.java
  lobby-client-http/src/test/java/org/triplea/http/client/lobby/login/LobbyLoginClientTest.java
  lobby/src/main/java/org/triplea/server/ServerConfiguration.java
  lobby/src/main/java/org/triplea/server/http/spark/controller/AnonymousUserLoginController.java
  lobby/src/main/java/org/triplea/server/http/spark/controller/ControllerConfiguration.java
  lobby/src/main/java/org/triplea/server/http/spark/controller/RegisteredUserLoginController.java
  lobby/src/test/java/org/triplea/server/http/spark/AnonymousUserLoginControllerTest.java
  lobby/src/test/java/org/triplea/server/http/spark/RegisteredUserLoginControllerTest.java
  lobby/src/test/java/org/triplea/server/http/spark/SparkServerSystemTest.java
Labels: PR: Feature Add

#4802 Convert 'Http server URI' to 'https port' and add default port values
  .idea/runConfigurations/SparkServer.xml
  config/triplea/schemas/lobby_server.json
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParser.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyServerProperties.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcher.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSettingSwingUiBinding.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParserTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcherIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcherTest.java
  game-headed/.eclipse/HeadedGameRunner.launch
  lobby_server.yaml
Labels: PR: Feature Update
