Repository triplea-game/triplea, pull requests merged in 2019-02, with the labels that each got.

#4681 Cleanup: Use consistent "toolTip" spelling
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportWindow.java
  swing-lib/src/main/java/org/triplea/swing/JLabelBuilder.java
Labels: PR: Refactor

#4680 Update: Error Message window LogRecord print handling
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/debug/ErrorMessageFormatter.java
  game-core/src/test/java/games/strategy/debug/ErrorMessageFormatterTest.java
Labels: PR: Feature Update

#4687 Wire up client to send errors to http server / Change 'shows details' button to 'report to TripleA'
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ConfirmationDialogController.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportConfiguration.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportUploadAction.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportWindow.java
  game-core/src/main/java/games/strategy/debug/error/reporting/ErrorReportWindowModel.java
  game-core/src/main/java/games/strategy/debug/error/reporting/PreviewWindow.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceErrorReportFormatter.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportModel.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportSwingView.java
  game-core/src/main/java/games/strategy/debug/error/reporting/StackTraceReportView.java
  game-core/src/main/java/games/strategy/debug/error/reporting/UserErrorReport.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/MetaSetupPanel.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/panels/main/MainPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/TimespanDialog.java
  game-core/src/main/java/games/strategy/triplea/settings/SettingsWindow.java
  game-core/src/main/java/games/strategy/triplea/ui/FindTerritoryDialog.java
  game-core/src/test/java/games/strategy/debug/error/reporting/ErrorReportConfigurationTest.java
  game-core/src/test/java/games/strategy/debug/error/reporting/ErrorReportUploadActionTest.java
  game-core/src/test/java/games/strategy/debug/error/reporting/StackTraceErrorReportFormatterTest.java
  game-core/src/test/java/games/strategy/debug/error/reporting/StackTraceReportModelTest.java
  game-core/src/test/java/games/strategy/debug/error/reporting/UserErrorReportTest.java
  http-client/src/main/java/org/triplea/http/client/FeignFactory.java
  http-client/src/main/java/org/triplea/http/client/error/report/create/ErrorReport.java
  http-client/src/main/java/org/triplea/http/client/github/issues/GithubIssueClient.java
  http-client/src/main/java/org/triplea/http/client/github/issues/GithubIssueClientFactory.java
  http-client/src/main/java/org/triplea/http/client/github/issues/create/CreateIssueRequest.java
  http-client/src/test/java/org/triplea/http/client/error/report/ErrorReportClientTest.java
  http-client/src/test/java/org/triplea/http/client/throttle/rate/RateLimitingThrottleTest.java
  http-client/src/test/java/org/triplea/http/client/throttle/size/MessageSizeThrottleTest.java
  http-server/src/main/java/org/triplea/server/reporting/error/ErrorReportRequestAdapter.java
  http-server/src/main/java/org/triplea/server/reporting/error/ErrorUploadConfiguration.java
  http-server/src/main/java/org/triplea/server/reporting/error/ErrorUploadStrategy.java
  http-server/src/test/java/org/triplea/server/http/spark/SparkServerSystemTest.java
  http-server/src/test/java/org/triplea/server/reporting/error/ErrorReportRequestAdapterTest.java
  http-server/src/test/java/org/triplea/server/reporting/error/ErrorUploadStrategyTest.java
  swing-lib/src/main/java/org/triplea/swing/JPanelBuilder.java
  swing-lib/src/main/java/org/triplea/swing/JTextAreaBuilder.java
  swing-lib/src/test/java/org/triplea/swing/JPanelBuilderTest.java
Labels: PR: Feature Add

#4673 Allow custom hostnames for bots
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
  game-core/src/main/java/games/strategy/engine/lobby/server/GameDescription.java
  game-core/src/main/java/games/strategy/net/Node.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyGameController.java
Labels: PR: Feature Add

#4714 Update: replace custom code with Guava 'not' Predicate
  game-core/src/main/java/games/strategy/engine/data/properties/MapProperty.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadList.java
  game-core/src/main/java/games/strategy/net/IpFinder.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/Matches.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  java-extras/src/main/java/org/triplea/java/Util.java
  java-extras/src/main/java/org/triplea/java/collections/CollectionUtils.java
  java-extras/src/main/java/org/triplea/java/function/NegationPredicate.java
  java-extras/src/test/java/org/triplea/java/UtilTest.java
Labels: PR: Refactor
