Repository triplea-game/triplea, pull requests merged in 2019-11, with the labels that each got.

#5441 Add parallel test configuration
  game-core/src/test/java/games/strategy/triplea/settings/AbstractClientSettingTestCase.java
  game-core/src/test/resources/junit-platform.properties
  http-server/src/test/resources/junit-platform.properties
  java-extras/src/test/resources/junit-platform.properties
  swing-lib/src/test/resources/junit-platform.properties
  test-common/src/test/resources/junit-platform.properties
Labels: PR: Dev Infrastructure

#5442 Extract ShowDialog with links to generic method
  game-core/src/main/java/games/strategy/debug/error/reporting/ConfirmationDialogController.java
  swing-lib/src/main/java/org/triplea/swing/SwingComponents.java
Labels: PR: More to Follow, PR: Refactor

#5444 Prep for future changes, rename LobbyServerProperties->ServerProperties
  game-core/src/main/java/games/strategy/debug/ErrorMessage.java
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/framework/startup/mc/SetupPanelModel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParser.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/net/ClientMessengerFactory.java
  game-core/src/main/java/org/triplea/live/servers/LiveServersFetcher.java
  game-core/src/main/java/org/triplea/live/servers/ServerProperties.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParserTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcherTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesTest.java
  smoke-testing/src/main/java/org/triplea/test/smoke/ClientConnect.java
Labels: PR: More to Follow, PR: Refactor

#5447 Remove API-key-generator from ServerQuarantineConversation
  game-core/src/main/java/games/strategy/net/IServerMessenger.java
  game-core/src/main/java/games/strategy/net/LocalNoOpMessenger.java
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
  game-core/src/main/java/games/strategy/net/nio/ServerQuarantineConversation.java
  lobby/src/main/java/org/triplea/lobby/server/LobbyServer.java
  lobby/src/main/java/org/triplea/lobby/server/api/key/ApiKeyGeneratorFactory.java
Labels: PR: Refactor

#5448 Infrastructure: Add README files to roles
  infrastructure/ansible/roles/admin_user/README.md
  infrastructure/ansible/roles/apt_update/README.md
  infrastructure/ansible/roles/bot/README.md
  infrastructure/ansible/roles/firewall/README.md
  infrastructure/ansible/roles/flyway/README.md
  infrastructure/ansible/roles/http_server/README.md
  infrastructure/ansible/roles/java/README.md
  infrastructure/ansible/roles/nginx/README.md
  infrastructure/ansible/roles/postgres/README.md
  infrastructure/ansible/roles/security/README.md
Labels: PR: Dev Infrastructure

#5449 Infrastructure: Update README notes
  infrastructure/README-SERVER-OPS.md
  infrastructure/README-VAGRANT-DEV.md
  infrastructure/README.md
Labels: PR: Dev Infrastructure

#5450 Infrastructure: status check scripts
  infrastructure/status-check/README.md
  infrastructure/status-check/check-prerelease-status
  infrastructure/status-check/prerelease-status
Labels: PR: Dev Infrastructure

#5451 Infrastructure: Move prod configuration to template
  http-server/configuration.yml
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
  infrastructure/ansible/roles/http_server/defaults/main.yml
  infrastructure/ansible/roles/http_server/templates/configuration.yml.j2
  infrastructure/ansible/roles/http_server/templates/http_server.service.j2
Labels: PR: Dev Infrastructure

#5452 Infrastructure: first pass of removing java lobby components
  infrastructure/ansible/group_vars/lobbyHosts.yml
  infrastructure/ansible/roles/lobby/defaults/main.yml
  infrastructure/ansible/roles/lobby/tasks/main.yml
  infrastructure/ansible/roles/lobby/templates/lobby.service.j2
  infrastructure/ansible/roles/lobby/templates/run_server.j2
Labels: PR: Dev Infrastructure

#5453 Infrastructure: Open additional bot ports
  infrastructure/ansible/group_vars/botHosts.yml
Labels: PR: Dev Infrastructure

#5454 Update Unit-Scroller Images (drop-shadow variant)
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerIcon.java
  game-headed/build.gradle
Labels: PR: Feature Update

#5456 Allow unit-scroller keybindings only when unit-scroller is visible
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
Labels: PR: Problem Fix

#5440 Isolate OutOfDate UI logic
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java
  game-core/src/main/java/games/strategy/engine/auto/update/OutOfDateDialog.java
Labels: PR: More to Follow, PR: Refactor

#5455 Fix KeyBindings firing while chatting
  swing-lib/src/main/java/org/triplea/swing/SwingComponents.java
Labels: PR: Problem Fix

#5461 Remove client-side password hashing on change password
  game-core/src/main/java/games/strategy/engine/lobby/client/login/ChangePasswordPanel.java
Labels: PR: More to Follow

#5462 AccessLogUpdater implementation
  http-server/src/main/java/org/triplea/server/user/account/login/AccessLogUpdater.java
  http-server/src/test/java/org/triplea/server/user/account/login/AccessLogUpdaterTest.java
  integration-testing/src/test/java/org/triplea/lobby/server/db/dao/access/log/AccessLogDaoTest.java
  integration-testing/src/test/resources/datasets/access_log/insert_anonymous_after.yml
  integration-testing/src/test/resources/datasets/access_log/insert_registered_after.yml
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/access/log/AccessLogDao.java
Labels: PR: More to Follow

#5464 Infrastructure: Update http run_server script
  infrastructure/ansible/roles/http_server/templates/run_server.j2
Labels: PR: Dev Infrastructure, PR: More to Follow

#5465 Infrastructure role, variable renaming & cleanups
  infrastructure/Vagrantfile
  infrastructure/ansible/group_vars/all.yml
  infrastructure/ansible/group_vars/dropwizardHosts.yml
  infrastructure/ansible/group_vars/prerelease.yml
  infrastructure/ansible/inventory/prerelease
  infrastructure/ansible/inventory/production
  infrastructure/ansible/inventory/vagrant
  infrastructure/ansible/roles/bot/defaults/main.yml
  infrastructure/ansible/roles/flyway/defaults/main.yml
  infrastructure/ansible/roles/flyway/tasks/main.yml
  infrastructure/ansible/roles/http_server/tasks/main.yml
  infrastructure/ansible/roles/lobby_database/tasks/main.yml
  infrastructure/ansible/roles/postgres/tasks/main.yml
  infrastructure/ansible/site.yml
Labels: PR: Dev Infrastructure, PR: More to Follow

#5463 Infrastructure: do not DL lobby jar
  infrastructure/run_deployment
Labels: PR: Dev Infrastructure, PR: More to Follow

#5472 Cleanup, remove unused DbUnit datasets
  integration-testing/src/test/resources/datasets/bad_words/user_data.yml
  integration-testing/src/test/resources/datasets/forgot_password/user_data.yml
Labels: PR: Refactor

#5481 Fix builds, Hack Travis to use Java 11.0.5
  .travis.yml
  .travis/do_release
  .travis/install_java_11.0.5
Labels: PR: Problem Fix

#5467 Refactor: use 'checkNotNull' for null arg check
  domain-data/src/main/java/org/triplea/domain/data/PlayerChatId.java
Labels: PR: Refactor

#5468 Fix LobbyLogin#showError flipped args bug
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
Labels: PR: Problem Fix

#5460 Use URI for server instead of host+port combination
  .travis/run_smoke_tests
  game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java
  game-core/src/main/java/games/strategy/engine/auto/update/OutOfDateDialog.java
  game-core/src/main/java/games/strategy/engine/framework/CliProperties.java
  game-core/src/main/java/games/strategy/engine/framework/GameRunner.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/CloseableDownloader.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/ContentDownloader.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/ContentReader.java
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadConfiguration.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ServerSetupPanel.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyPropertyFetcherConfiguration.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParser.java
  game-core/src/main/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
  game-core/src/main/java/games/strategy/net/ClientMessengerFactory.java
  game-core/src/main/java/games/strategy/triplea/UrlConstants.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSetting.java
  game-core/src/main/java/games/strategy/triplea/settings/ClientSettingSwingUiBinding.java
  game-core/src/main/java/games/strategy/triplea/settings/SelectionComponentFactory.java
  game-core/src/main/java/org/triplea/debug/ErrorMessage.java
  game-core/src/main/java/org/triplea/game/server/HeadlessGameServer.java
  game-core/src/main/java/org/triplea/game/server/HeadlessServerSetup.java
  game-core/src/main/java/org/triplea/live/servers/CurrentVersionSelector.java
  game-core/src/main/java/org/triplea/live/servers/FetchingCache.java
  game-core/src/main/java/org/triplea/live/servers/LiveServers.java
  game-core/src/main/java/org/triplea/live/servers/LiveServersFetcher.java
  game-core/src/main/java/org/triplea/live/servers/ServerProperties.java
  game-core/src/main/java/org/triplea/live/servers/ServerYamlParser.java
  game-core/src/test/java/games/strategy/engine/ClientContextIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/ContentDownloaderIntegrationTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/ContentDownloaderTest.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/ContentReaderTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyPropertyFileParserTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesFetcherTest.java
  game-core/src/test/java/games/strategy/engine/lobby/client/login/LobbyServerPropertiesTest.java
  game-core/src/test/java/org/triplea/live/servers/CurrentVersionSelectorTest.java
  game-core/src/test/java/org/triplea/live/servers/FetchingCacheTest.java
  game-core/src/test/java/org/triplea/live/servers/LiveServersFetcherIntegrationTest.java
  game-core/src/test/java/org/triplea/live/servers/LiveServersFetcherTest.java
  game-core/src/test/java/org/triplea/live/servers/ServerYamlParserTest.java
  game-core/src/test/java/org/triplea/live/servers/ServerYamlValidityTest.java
  game-core/src/test/resources/live.servers.yaml.examples/servers_example.yaml
  game-headed/src/main/java/org/triplea/game/client/ui/javafx/util/ClientSettingJavaFxUiBinding.java
  game-headless/scripts/run_bot
  game-headless/scripts/run_bot.bat
  lobby_server.yaml
  servers.yml
  smoke-testing/build.gradle
  smoke-testing/src/main/java/org/triplea/test/smoke/ClientConnect.java
  test-common/src/main/java/org/triplea/test/common/StringToInputStream.java
  test-common/src/main/java/org/triplea/test/common/TestDataFileReader.java
  test-common/src/test/java/org/triplea/test/common/StringToInputStreamTest.java
  test-common/src/test/java/org/triplea/test/common/TestDataFileReaderTest.java
  test-common/src/test/resources/example/example_file.txt
Labels: PR: More to Follow

#5466 Remove moderator boot-game button in favor of context menu
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java
Labels: PR: Feature Removal

#5469 Fix copy/paste error in BanTimeUnit
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/action/BanTimeUnit.java
Labels: PR: Problem Fix

#5471 Anonymous login disallow duplicate names
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
  http-server/src/main/java/org/triplea/server/lobby/chat/event/processing/Chatters.java
  http-server/src/main/java/org/triplea/server/user/account/login/LoginControllerFactory.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/anonymous/AnonymousLogin.java
  http-server/src/main/java/org/triplea/server/user/account/login/authorizer/anonymous/AnonymousLoginFactory.java
  http-server/src/test/java/org/triplea/server/lobby/chat/event/processing/ChattersTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/authorizer/anonymous/AnonymousLoginTest.java
Labels: PR: Feature Update, PR: More to Follow

#5473 Unit-scroller rendering
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/AvatarPanelFactory.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Feature Update

#5470 Fix message sender to check for an open session
  http-server/src/main/java/org/triplea/server/lobby/chat/MessageSender.java
Labels: PR: Problem Fix

#5416 Batch AI amphibious moves.
  game-core/src/main/java/games/strategy/triplea/TripleAPlayer.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProNonCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/MoveBatcher.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProMoveUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/weak/WeakAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/MovePerformer.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveValidator.java
  game-core/src/main/java/games/strategy/triplea/delegate/SpecialMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/data/MoveDescription.java
  game-core/src/main/java/games/strategy/triplea/delegate/remote/IMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/test/java/games/strategy/triplea/ai/pro/util/MoveBatcherTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveDelegateTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveValidatorTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
Labels: PR: Feature Update

#5506 Check links
  .travis.yml
  .travis/check-links
  game-core/src/main/java/games/strategy/engine/framework/GameDataManager.java
  game-core/src/main/java/games/strategy/triplea/UrlConstants.java
Labels: PR: Dev Infrastructure, PR: Problem Fix

#5509 Set min-size of action panel to 240px
  game-core/src/main/java/games/strategy/triplea/ui/ActionPanel.java
Labels: PR: Feature Update

#5510 Unit Scroller Updates: "station", rename images + wake-all button
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerIcon.java
  game-headed/build.gradle
Labels: PR: Feature Add, PR: Feature Update

#5512 Fix Travis config to run pmdTest
  .travis.yml
  game-core/src/test/java/games/strategy/triplea/ai/pro/util/MoveBatcherTest.java
Labels: PR: Problem Fix

#5513 Cleanup: Weaken types and newly unnecessary casts
  game-core/src/test/java/games/strategy/triplea/delegate/RevisedTest.java
Labels: PR: Refactor

#5514 Cleanup: Remove unhelpful comment
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractMoveExtendedDelegateState.java
Labels: PR: Refactor

#5515 Cleanup: Simplify return statement
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractPlaceDelegate.java
Labels: PR: Refactor

#5516 Cleanup: Remove unused methods and use "@UtilityClass" annotation
  game-core/src/test/java/games/strategy/triplea/delegate/GameDataTestUtil.java
Labels: PR: Refactor

#5517 Cleanup: Weaken types
  game-core/src/test/java/games/strategy/triplea/delegate/LhtrTest.java
Labels: PR: Refactor

#5518 Cleanup: Inline constant value parameter, bombing is always false
  game-core/src/test/java/games/strategy/triplea/delegate/AirThatCantLandUtilTest.java
Labels: PR: Refactor

#5519 Cleanup: Weaken type and remove unnecessary cast
  game-core/src/test/java/games/strategy/triplea/delegate/MustFightBattleTest.java
Labels: PR: Refactor

#5520 Cleanup: Remove unused variable
  game-core/src/test/java/games/strategy/triplea/delegate/AbstractDelegateTestCase.java
Labels: PR: Refactor

#5521 Cleanup: Inline class variable to a local variable
  game-core/src/test/java/games/strategy/triplea/delegate/PlaceDelegateTest.java
Labels: PR: Refactor

#5522 Cleanup: Remove unnecessary throws declaration and weaken types
  game-core/src/test/java/games/strategy/triplea/delegate/TerritoryEffectHelperTest.java
Labels: PR: Refactor

#5523 Cleanup: Weaken types and remove unnecessary cast
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year42Test.java
Labels: PR: Refactor

#5532 Remove unused 'isProduction' variable
  http-server/src/main/java/org/triplea/server/error/reporting/CreateIssueStrategy.java
  http-server/src/main/java/org/triplea/server/error/reporting/ErrorReportControllerFactory.java
  http-server/src/test/java/org/triplea/server/error/reporting/CreateIssueStrategyTest.java
Labels: PR: Refactor

#5533 Remove http-server env variable startup check
  http-server/src/main/java/org/triplea/server/http/AppConfig.java
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
Labels: PR: Feature Removal

#5530 Implement moderator ban & disconnect
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/BanPlayerRequest.java
  http-clients/src/main/java/org/triplea/http/client/lobby/moderator/ModeratorChatClient.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/BanPlayerRequestTest.java
  http-clients/src/test/java/org/triplea/http/client/lobby/moderator/ModeratorChatClientTest.java
  http-server/src/main/java/org/triplea/server/http/ServerApplication.java
  http-server/src/main/java/org/triplea/server/lobby/chat/ChatParticipantAdapter.java
  http-server/src/main/java/org/triplea/server/lobby/chat/MessageBroadcaster.java
  http-server/src/main/java/org/triplea/server/lobby/chat/MessagingService.java
  http-server/src/main/java/org/triplea/server/lobby/chat/event/processing/Chatters.java
  http-server/src/main/java/org/triplea/server/lobby/chat/moderation/ModeratorActionPersistence.java
  http-server/src/main/java/org/triplea/server/lobby/chat/moderation/ModeratorChatController.java
  http-server/src/main/java/org/triplea/server/lobby/chat/moderation/ModeratorChatControllerFactory.java
  http-server/src/main/java/org/triplea/server/lobby/chat/moderation/ModeratorChatService.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/banned/users/UserBanControllerFactory.java
  http-server/src/main/java/org/triplea/server/moderator/toolbox/banned/users/UserBanService.java
  http-server/src/main/java/org/triplea/server/user/account/login/LoginModule.java
  http-server/src/test/java/org/triplea/server/lobby/chat/ChatParticipantAdapterTest.java
  http-server/src/test/java/org/triplea/server/lobby/chat/MessageBroadcasterTest.java
  http-server/src/test/java/org/triplea/server/lobby/chat/MessagingServiceTest.java
  http-server/src/test/java/org/triplea/server/lobby/chat/event/processing/ChattersTest.java
  http-server/src/test/java/org/triplea/server/lobby/chat/moderation/ModeratorActionPersistenceTest.java
  http-server/src/test/java/org/triplea/server/lobby/chat/moderation/ModeratorChatServiceTest.java
  http-server/src/test/java/org/triplea/server/moderator/toolbox/banned/users/UserBanServiceTest.java
  http-server/src/test/java/org/triplea/server/user/account/login/LoginModuleTest.java
  integration-testing/src/test/java/org/triplea/lobby/server/db/dao/TempPasswordDaoTest.java
  integration-testing/src/test/java/org/triplea/lobby/server/db/dao/UserJdbiDaoTest.java
  integration-testing/src/test/java/org/triplea/lobby/server/db/dao/api/key/LobbyApiKeyDaoTest.java
  integration-testing/src/test/java/org/triplea/server/lobby/chat/moderation/ModeratorLobbyControllerIntegrationTest.java
  integration-testing/src/test/resources/datasets/integration.yml
  integration-testing/src/test/resources/datasets/temp_password/invalidate_password.yml
  integration-testing/src/test/resources/datasets/user/change_password_after.yml
  integration-testing/src/test/resources/datasets/user/change_password_before.yml
  integration-testing/src/test/resources/datasets/user/create_user_after.yml
  integration-testing/src/test/resources/datasets/user/create_user_before.yml
  integration-testing/src/test/resources/datasets/user/get_legacy_password.yml
  integration-testing/src/test/resources/datasets/user/initial.yml
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/JdbiDatabase.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/ModeratorAuditHistoryDao.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/api/key/ApiKeyRecord.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/api/key/LobbyApiKeyDao.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/api/key/LobbyApiKeyDaoWrapper.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/api/key/PlayerIdLookup.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/api/key/UserWithRoleRecord.java
  lobby-db-dao/src/main/java/org/triplea/lobby/server/db/dao/user/ban/UserBanDao.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/api/key/LobbyApiKeyDaoWrapperTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/api/key/PlayerIdLookupTest.java
  lobby-db-dao/src/test/java/org/triplea/lobby/server/db/dao/api/key/UserWithRoleRecordTest.java
Labels: PR: Feature Add

#5535 Remove environment variable from integration-testing configuration
  integration-testing/configuration-testing.yml
Labels: PR: Refactor

#5536 Update run_deployment: do not redownload jars and fixes
  infrastructure/run_deployment
Labels: PR: Dev Infrastructure

#5537 Deployment updates: use lobby-uri & fixes
  infrastructure/ansible/group_vars/all.yml
  infrastructure/ansible/group_vars/prerelease.yml
  infrastructure/ansible/group_vars/production.yml
  infrastructure/ansible/group_vars/vagrant.yml
  infrastructure/ansible/roles/bot/defaults/main.yml
  infrastructure/ansible/roles/bot/templates/run_server.j2
  infrastructure/ansible/roles/http_server/defaults/main.yml
  infrastructure/ansible/roles/http_server/tasks/main.yml
  infrastructure/ansible/roles/http_server/templates/configuration.yml.j2
Labels: PR: Dev Infrastructure

#5538 Fix double '-jar' typo in run_server.j2
  infrastructure/ansible/roles/http_server/templates/run_server.j2
Labels: PR: Dev Infrastructure

#5541 Log address of bot when connecting
  game-core/src/main/java/games/strategy/net/ClientMessengerFactory.java
Labels: PR: Feature Update

#5543 Improve 'Timers' Builder and Fix Websocket Inactivity Disconnect
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
  http-clients/src/main/java/org/triplea/http/client/web/socket/WebSocketConnection.java
  java-extras/src/main/java/org/triplea/java/timer/ScheduledTimer.java
  java-extras/src/main/java/org/triplea/java/timer/Timers.java
Labels: PR: Problem Fix, PR: Refactor

#5544 Change PR template wording "bug" -> "problem"
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Configuration Update

#5546 Infrastructure .gitignore to ignore flyway migrations zip
  infrastructure/.gitignore
Labels: PR: Configuration Update

#5505 AI unit purchase upgrade logic improvements
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProPurchaseAi.java
Labels: PR: Feature Update

#5539 Invert deployment ordering of nginx and dropwizard
  infrastructure/ansible/site.yml
Labels: PR: Dev Infrastructure

#5547 Infrastructure UFW port configuration & remove Nginx cert generation
  infrastructure/ansible/group_vars/botHosts.yml
  infrastructure/ansible/group_vars/dropwizardHosts.yml
  infrastructure/ansible/roles/bot/defaults/main.yml
  infrastructure/ansible/roles/bot/tasks/main.yml
  infrastructure/ansible/roles/firewall/defaults/main.yml
  infrastructure/ansible/roles/firewall/tasks/main.yml
  infrastructure/ansible/roles/nginx/defaults/main.yml
  infrastructure/ansible/roles/nginx/tasks/main.yml
Labels: PR: Dev Infrastructure, PR: Problem Fix

#5542 Websocket fixes for HTTPS & Disconnect Handling
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModel.java
  http-clients/src/main/java/org/triplea/http/client/lobby/HttpLobbyClient.java
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/InboundChat.java
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/LobbyChatClient.java
  http-clients/src/main/java/org/triplea/http/client/web/socket/GenericWebSocketClient.java
  http-clients/src/test/java/org/triplea/http/client/lobby/chat/LobbyChatClientTest.java
  http-clients/src/test/java/org/triplea/http/client/web/socket/GenericWebSocketClientTest.java
Labels: PR: Feature Update, PR: Problem Fix

#5548 Update NGINX config for ciphers & websocket port forwarding
  infrastructure/ansible/roles/nginx/templates/etc_nginx_sites_enabled_default.j2
Labels: PR: Configuration Update, PR: Dev Infrastructure

#5503 Refactor move code to use MoveDescription objects.
  game-core/src/main/java/games/strategy/engine/data/AbstractMoveDescription.java
  game-core/src/main/java/games/strategy/engine/data/MoveDescription.java
  game-core/src/main/java/games/strategy/triplea/TripleAPlayer.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/ProNonCombatMoveAi.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/MoveBatcher.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProMoveUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/weak/WeakAi.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/AbstractUndoableMove.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/MovePerformer.java
  game-core/src/main/java/games/strategy/triplea/delegate/MoveValidator.java
  game-core/src/main/java/games/strategy/triplea/delegate/SpecialMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/delegate/UndoableMove.java
  game-core/src/main/java/games/strategy/triplea/delegate/data/MoveDescription.java
  game-core/src/main/java/games/strategy/triplea/delegate/data/PlacementDescription.java
  game-core/src/main/java/games/strategy/triplea/delegate/remote/IMoveDelegate.java
  game-core/src/main/java/games/strategy/triplea/ui/AbstractMovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/ActionButtons.java
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java
  game-core/src/main/java/games/strategy/triplea/ui/history/HistoryDetailsPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/history/HistoryLog.java
  game-core/src/test/java/games/strategy/triplea/ai/pro/util/MoveBatcherTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/GameDataTestUtil.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveDelegateTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveValidatorTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/PacificTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/RevisedTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year42Test.java
Labels: PR: Refactor

#5556 Add automatic prerelease deployment to travis
  .travis.yml
  infrastructure/README.md
  infrastructure/ansible/site.yml
  infrastructure/run_deployment
Labels: PR: Dev Infrastructure

#5572 Simplify ContentReader
  game-core/src/main/java/games/strategy/engine/framework/map/download/ContentReader.java
  game-core/src/test/java/games/strategy/engine/framework/map/download/ContentReaderTest.java
Labels: PR: Refactor

#5579 Fix potential NPE, return empty collection instead of null
  game-core/src/main/java/games/strategy/triplea/attachments/TerritoryAttachment.java
Labels: PR: Problem Fix

#5581 UnitAttachment cleanup: Remove always false if conditions
  game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
Labels: PR: Refactor

#5582 Fix potential NPEs
  game-core/src/main/java/games/strategy/triplea/delegate/MoveValidator.java
  game-core/src/main/java/games/strategy/triplea/ui/MapUnitTooltipManager.java
  game-core/src/main/java/tools/image/PolygonGrabber.java
Labels: PR: Problem Fix

#5583 Fix potential null unboxing
  http-server/src/main/java/org/triplea/server/lobby/game/listing/GameListingController.java
Labels: PR: Refactor

#5584 Fix value might be null
  game-core/src/main/java/games/strategy/engine/data/GameParser.java
Labels: PR: Problem Fix

#5585 Replace constant-valued variables with the constant value
  game-core/src/main/java/games/strategy/engine/data/Route.java
  game-core/src/main/java/games/strategy/triplea/TripleAPlayer.java
  game-core/src/main/java/games/strategy/triplea/attachments/TriggerAttachment.java
  game-core/src/main/java/games/strategy/triplea/attachments/UnitSupportAttachment.java
  game-core/src/main/java/games/strategy/triplea/delegate/BattleTracker.java
  game-core/src/main/java/games/strategy/triplea/delegate/EditValidator.java
Labels: PR: Refactor

#5590 Break long chat lines
  http-clients/src/main/java/org/triplea/http/client/lobby/chat/events/server/ChatMessage.java
  http-clients/src/test/java/org/triplea/http/client/lobby/chat/events/server/ChatMessageTest.java
Labels: PR: Feature Update

#5593 Sonar fix: Use BigDecimal.valueOf(double) instead of new BigDecimal(double)
  game-core/src/main/java/games/strategy/engine/data/properties/DoubleProperty.java
Labels: PR: Problem Fix

#5595 Remove unused 'JTable' parameter
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/moderators/ModeratorsTab.java
  game-core/src/main/java/games/strategy/engine/lobby/moderator/toolbox/tabs/moderators/ModeratorsTabActions.java
Labels: PR: Refactor

#5596 Remove throws IllegalStart and IllegalArg exception declarations
  game-core/src/main/java/games/strategy/engine/delegate/DefaultDelegateBridge.java
  game-core/src/main/java/games/strategy/engine/random/PbemDiceRoller.java
Labels: PR: Refactor

#5594 Remove commented out code
  domain-data/src/main/java/org/triplea/domain/data/PlayerEmailValidation.java
  game-core/src/main/java/games/strategy/engine/auto/update/OutOfDateDialog.java
  game-core/src/main/java/games/strategy/engine/data/GameParser.java
  game-core/src/main/java/games/strategy/engine/data/ResourceCollection.java
  game-core/src/main/java/games/strategy/engine/data/XmlReader.java
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java
  game-core/src/main/java/games/strategy/triplea/Constants.java
  game-core/src/main/java/games/strategy/triplea/attachments/PlayerAttachment.java
Labels: PR: Refactor

#5599 Cleanup: remove api key and change password flags from socket connection
  game-core/src/main/java/games/strategy/net/ClientMessenger.java
  game-core/src/main/java/games/strategy/net/IClientMessenger.java
  game-core/src/main/java/games/strategy/net/Messengers.java
  game-core/src/main/java/games/strategy/net/nio/ClientQuarantineConversation.java
Labels: PR: Refactor

#5601 Remove 'ifPresentOrElse' utility
  game-core/src/main/java/games/strategy/engine/framework/map/download/DownloadMapsWindow.java
  game-core/src/main/java/games/strategy/triplea/ui/UnitIconProperties.java
  java-extras/src/main/java/org/triplea/java/OptionalUtils.java
  java-extras/src/test/java/org/triplea/java/OptionalUtilsTest.java
Labels: PR: Refactor

#5586 Allow build or download of deployment artifacts
  .travis.yml
  infrastructure/build_deployment_artifacts
  infrastructure/download_deployment_artifacts
  infrastructure/run_deployment
Labels: PR: Configuration Update, PR: Dev Infrastructure

#5597 Add sonarqube config
  .travis.yml
  build.gradle
Labels: PR: Configuration Update, PR: Dev Infrastructure

#5604 Update travis build - correct script name and upload artifacts in parallel
  .travis.yml
Labels: PR: Dev Infrastructure, PR: Problem Fix

#5605 Travis Cache JDK and Remove '--no-daemon'
  .travis.yml
Labels: PR: Dev Infrastructure

#5617 Add 'volatile' keyword back to MapDownloadProgressListener download length
  game-core/src/main/java/games/strategy/engine/framework/map/download/MapDownloadProgressListener.java
Labels: PR: Problem Fix

#5612 Cleaner travis desc
  .travis.yml
Labels: PR: Dev Infrastructure

#5615 Update IDEA headless launcher to use 'triplea.lobby.uri' parameter
  .idea/runConfigurations/HeadlessGameRunner.xml
Labels: PR: Problem Fix

#5609 Fix arithmetic expressions done as integer
  game-core/src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcher.java
  game-core/src/main/java/games/strategy/engine/framework/ui/GameChooser.java
  game-core/src/main/java/games/strategy/engine/lobby/client/ui/action/BanTimeUnit.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/data/ProPurchaseOption.java
  game-core/src/main/java/games/strategy/triplea/ui/MapPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/RouteDescription.java
  game-core/src/main/java/tools/map/making/ConnectionFinder.java
Labels: PR: Problem Fix

#5618 Travis update: Run sonar only on master
  .travis.yml
Labels: PR: Dev Infrastructure

#5614 Minor error messaging edits/fixes
  game-core/src/main/java/games/strategy/net/ServerMessenger.java
Labels: PR: Cleanup/Simplification, PR: Problem Fix
