Repository triplea-game/triplea, pull requests merged in 2020-02, with the labels that each got.

#5898 Build update: Handle non-zero exit code when map descriptor files are updated
  .travis/do_release
Labels: PR: Post-Merge Review

#5871 Enhance suicide functionality and deprecate old suicide options
  game-core/src/main/java/games/strategy/triplea/ai/pro/data/ProPurchaseOptionMap.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProBattleUtils.java
  game-core/src/main/java/games/strategy/triplea/ai/pro/util/ProSortMoveOptionsUtils.java
  game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
  game-core/src/main/java/games/strategy/triplea/delegate/AirMovementValidator.java
  game-core/src/main/java/games/strategy/triplea/delegate/DiceRoll.java
  game-core/src/main/java/games/strategy/triplea/delegate/Matches.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/AirBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/BattleStepStrings.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/BattleTracker.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/CasualtySelector.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/Fire.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/MustFightBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/StrategicBombingRaidBattle.java
  game-core/src/main/java/games/strategy/triplea/delegate/battle/TargetGroup.java
  game-core/src/main/java/games/strategy/triplea/odds/calculator/BattleCalculatorPanel.java
  game-core/src/main/java/games/strategy/triplea/ui/BattleDisplay.java
  game-core/src/test/java/games/strategy/triplea/delegate/DiceRollTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/GameDataTestUtil.java
  game-core/src/test/java/games/strategy/triplea/delegate/MoveDelegateTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/PacificTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/RevisedTest.java
  game-core/src/test/java/games/strategy/triplea/delegate/WW2V3Year41Test.java
  game-core/src/test/java/games/strategy/triplea/delegate/battle/TargetGroupTest.java
Labels: PR: Feature Add

#5933 Fix Targets Including Dead Units Bug
  game-core/src/main/java/games/strategy/triplea/delegate/battle/Fire.java
Labels: PR: Problem Fix

#5966 Avoid unnecessary unit scroller rendering
  game-core/src/main/java/games/strategy/triplea/ui/MovePanel.java
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Problem Fix

#5967 Compute units to render in unit scroller before adding a task to EDT
  game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScroller.java
Labels: PR: Problem Fix

#5968 Thread safe collection utils
  java-extras/src/main/java/org/triplea/java/collections/CollectionUtils.java
Labels: PR: Problem Fix

#5971 Report build script failure script fix, report master branch failures only
  .travis/shared/report-build-status
Labels: PR: Problem Fix
